### ISSUE TITLE
[BUG] cn.escheduler.api.controller.ResourcesController:[313] - create resource file online error

### ISSUE THREAD

**Issue by shaozhipeng** [apache/incubator-dolphinscheduler#1164]
**Describe the bug**
cn.escheduler.api.controller.ResourcesController:[313] - create resource file online error.

**To Reproduce**
1. 进入 资源中心-文件管理
2. 点击 创建文件
3. 输入完必填项后点击创建

**Log**
[ERROR] 2019-11-06 14:01:46.177 cn.escheduler.api.controller.ResourcesController:[313] - create resource file online error
java.lang.NullPointerException: null
        at cn.escheduler.api.service.ResourcesService.verifyResourceName(ResourcesService.java:445)
        at cn.escheduler.api.service.ResourcesService.onlineCreateResource(ResourcesService.java:580)
        at cn.escheduler.api.service.ResourcesService$$FastClassBySpringCGLIB$$ad56f2d2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at cn.escheduler.api.service.ResourcesService$$EnhancerBySpringCGLIB$$a1f86aa3.onlineCreateResource(<generated>)
        at cn.escheduler.api.controller.ResourcesController.onlineCreateResource(ResourcesController.java:311)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)

**Comment by shaozhipeng** [comment]
VERSION 1.1.0
After checking the code, it was found that the login user lacked tenants, but the creation file did not give a clear hint, but directly reported the null pointer.

ResourcesService#verifyResourceName#String tenantCode = tenantMapper.queryById(loginUser.getTenantId()).getTenantCode();

And Security center - user management - edit user, the edit page password box is clear text display.
