### ISSUE TITLE
[BUG] Hive-1.1.0-CDH not supported cause missing field 'client_protocol'

### ISSUE THREAD

**Issue by feifanlee** [apache/incubator-dolphinscheduler#1356]
**Describe the bug**
I tried to connect my CDH hive-1.1.0 but failed with following logs:
```
[ERROR] 2019-11-29 17:01:38.579 org.apache.hive.jdbc.HiveConnection:[600] - Error opening session
org.apache.thrift.TApplicationException: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=default})
...
...
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.TApplicationException: Required field 'client_protocol' is unset! Struct:TOpenSessionReq(client_protocol:null, configuration:{use:database=default})
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
...
...
```

**To Reproduce**
data source management -> create datasource -> hive/impala -> use my cdh-hive datasource -> test connection

**Expected behavior**
connection success

**Screenshots**

connection datasource failure

**Which version of Dolphin Scheduler:**
 -[1.1.0]

**Comment by dailidong** [comment]
it‘s easy to fix, who want to fix it?

**Comment by Yeleights** [comment]
In dolphinscheduler-1.1.0, hive-jdbc version is 2.1.0.
change hive-jdbc version 2.1.0 -> version 1.1.0 can support CDH-hive 1.1.0

> <dependency>
    <groupId>org.apache.hive</groupId>
    <artifactId>hive-jdbc</artifactId>
    <version>2.1.0</version>
</dependency>

> <dependency>
    <groupId>org.apache.hive</groupId>
    <artifactId>hive-jdbc</artifactId>
    <version>1.1.0</version>
</dependency>

**Comment by LINKPEF** [comment]
Would you tell me where to find the pom.xml file to update?
