### ISSUE TITLE
[QUESTION] Spark task exception

### ISSUE THREAD

**Issue by uuyuu** [apache/incubator-dolphinscheduler#2022]
I write a very simple spark app, and I compile it to a jar, after I upload to DS, I create a workflow and add a spark node, then select the jar, I run the workflow, but it failed, I get an error from dolphinscheduler-worker.log:
`[ERROR] 2020-02-26 07:08:20.698 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[152] - task scheduler failure
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): org.apache.dolphinscheduler.dao.mapper.ResourceMapper.listAuthorizedResource
at org.apache.ibatis.binding.MapperMethodSqlCommand.<init>(MapperMethod.java:235)atcom.baomidou.mybatisplus.core.override.MybatisMapperMethod.<init>(MybatisMapperMethod.java:49)atcom.baomidou.mybatisplus.core.override.MybatisMapperProxy.lambdacachedMapperMethod0(MybatisMapperProxy.java:65)atjava.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)atcom.baomidou.mybatisplus.core.override.MybatisMapperProxy.cachedMapperMethod(MybatisMapperProxy.java:65)atcom.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:60)atcom.sun.proxy.Proxy88.listAuthorizedResource(Unknown Source)
at org.apache.dolphinscheduler.service.process.ProcessService.listUnauthorized(ProcessService.java:1793)
at org.apache.dolphinscheduler.service.process.ProcessService
FastClassBySpringCGLIB
ed138739.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
at org.springframework.aop.framework.CglibAopProxyDynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)atorg.apache.dolphinscheduler.service.process.ProcessServiceEnhancerBySpringCGLIB3738bbca.listUnauthorized(<generated>)atorg.apache.dolphinscheduler.service.permission.PermissionCheck.checkPermission(PermissionCheck.java:147)atorg.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.checkDownloadPermission(TaskScheduleThread.java:338)atorg.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.downloadResource(TaskScheduleThread.java:308)atorg.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:101)atjava.util.concurrent.ExecutorsRunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`
I cannot find the  reason, please help me, thanks a lot.

**Comment by dailidong** [comment]
does this problem solved or not?

**Comment by uuyuu** [comment]
> does this problem solved or not?

well, I didn't find the reason finally. Maybe other people didn't install DS correctly, I reinstall it in a new CentOS docker,  this issue not risen again. I will close this issue.

**Comment by soul-zym** [comment]
Replacing all files under conf/org should be able to solve this problem. I encountered this problem when Upgrading 1.3.2 to 1.3.3, because I used the old version of conF/file when upgrading.
/ org/apache/dolphinscheduler/dao/mapper/ProcessDefinitionMapper. Replace XML for the new after after I met the problem was solved
