### ISSUE TITLE
[BUG] java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.readStringRequireUtf8()Ljava/lang/String;

### ISSUE THREAD

**Issue by yaoh599** [apache/incubator-dolphinscheduler#2036]
logger-server启动后，一直报

Exception in thread "grpc-default-executor-0" java.lang.NoSuchMethodError: com.google.protobuf.CodedInputStream.readStringRequireUtf8()Ljava/lang/String;
	at cn.escheduler.rpc.LogParameter.<init>(LogParameter.java:61)
	at cn.escheduler.rpc.LogParameter.<init>(LogParameter.java:14)
	at cn.escheduler.rpc.LogParameter$1.parsePartialFrom(LogParameter.java:699)
	at cn.escheduler.rpc.LogParameter$1.parsePartialFrom(LogParameter.java:694)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:89)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parseFrom(ProtoLiteUtils.java:173)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:165)
	at io.grpc.protobuf.lite.ProtoLiteUtils$2.parse(ProtoLiteUtils.java:82)
	at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:287)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:252)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:626)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gabrywu** [comment]
you should check the lib dir if have multi version ,like  protobuf-java-*.jar

**Comment by dailidong** [comment]
do you solve this problem?

**Comment by dailidong** [comment]
just temporary close， if not solved , you can reopen
