### ISSUE TITLE
the question about starting api server

### ISSUE THREAD

**Issue by barntt77** [apache/incubator-dolphinscheduler#2073]
when i want to start api server ,meet this question, need help .I have tested the same configuration locally, but have had this problem on the server
![image](https://user-images.githubusercontent.com/54257101/75846201-8745a000-5e16-11ea-98bd-7acc91f35ef2.png)

**Comment by lgcareer** [comment]
You need config the database of application.properties before run create-dolphinscheduler.sh

**Comment by dailidong** [comment]
has this issue solved or not ?

**Comment by barntt77** [comment]
> has this issue solved or not ?

when i start those server ,such as api-server , master-server,work-server....，meet this question
![image](https://user-images.githubusercontent.com/54257101/77022165-dd444700-69c3-11ea-89a0-028e069c993c.png)
Logging system failed to initialize using configuration from '/opt/soft/dolphinscheduler/conf/apiserver_logback.xml'
java.io.FileNotFoundException: /opt/soft/dolphinscheduler/conf/apiserver_logback.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:297)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:266)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:229)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:202)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:347)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:32)

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved, if not, please check whether /opt/soft/dolphinscheduler/conf/apiserver_logback.xml exists and the permissions are correct
