### ISSUE TITLE
Does ds support hive1 datasource?

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#2414]
Does ds support hive1 datasource? when testing hive1 datasource, below exception occurrs.

Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.thrift.TFilterTransport
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 89 common frames omitted

**Comment by dailidong** [comment]
for now, DS lib dir use hive 2,  so maybe not support hive1 default,  and you can  try replace the relvant hive2 jars to 1, and try

**Comment by Eights-Li** [comment]
Adapting to different Hive versions requires source code compilation and deployment。
You can modify the hive version in pom. 
In FAQ doc end have a example change the hive version to 1.1.0.
ps：[https://dolphinscheduler.apache.org/en-us/docs/release/faq.html](url)

**Comment by geosmart** [comment]
> Adapting to different Hive versions requires source code compilation and deployment。
> You can modify the hive version in pom.
> In FAQ doc end have a example change the hive version to 1.1.0.
> ps：[https://dolphinscheduler.apache.org/en-us/docs/release/faq.html](url)

url changed to https://dolphinscheduler.apache.org/en-us/docs/release/faq.html

**Comment by geosmart** [comment]
org.apache.hadoop.hive.thrift.TFilterTransport is class in hive-exec
I resolve it by add `hive-exec ` to root pom.xml
thank  @felix-thinkingdata  

```
            <dependency>
                <groupId>org.apache.hive</groupId>
                <artifactId>hive-jdbc</artifactId>
                <version>${hive.jdbc.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.hive</groupId>
                <artifactId>hive-exec</artifactId>
                <version>${hive.jdbc.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>jline</artifactId>
                        <groupId>jline</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>log4j</artifactId>
                        <groupId>log4j</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>antlr-runtime</artifactId>
                        <groupId>org.antlr</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>jackson-mapper-asl</artifactId>
                        <groupId>org.codehaus.jackson</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>jackson-core-asl</artifactId>
                        <groupId>org.codehaus.jackson</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>apache-log4j-extras</artifactId>
                        <groupId>log4j</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>slf4j-log4j12</artifactId>
                        <groupId>org.slf4j</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>hive-ant</artifactId>
                        <groupId>org.apache.hive</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>hive-shims-0.23</artifactId>
                        <groupId>org.apache.hive.shims</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>hive-shims</artifactId>
                        <groupId>org.apache.hive</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>calcite-core</artifactId>
                        <groupId>org.apache.calcite</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>janino</artifactId>
                        <groupId>org.codehaus.janino</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>calcite-avatica</artifactId>
                        <groupId>org.apache.calcite</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
				 
```

**Comment by geosmart** [comment]
just close

**Comment by shiliquan** [comment]
我用的1.3.2的也遇到了这个问题 ，请问怎么解决啊？ 我是通过tar包来安装的，找不到pom.xml,
![Catch(09-23-01-07-41)](https://user-images.githubusercontent.com/42087586/93917218-48892000-fd3d-11ea-95db-97879ea8a0f7.jpg)
