### ISSUE TITLE
[BUG] Instance must be started before calling this method

### ISSUE THREAD

**Issue by elitecodegroovy** [apache/incubator-dolphinscheduler#2437]
**Describe the bug**
WorkerServer was shutdown with the following error:

```

[INFO] 2020-04-16 13:50:59.804 org.apache.dolphinscheduler.common.zk.ZookeeperCachedOperator:[47] - add listener to zk path: /dolphinscheduler
[INFO] 2020-04-16 13:51:01.102 org.apache.dolphinscheduler.server.worker.WorkerServer:[59] - Started WorkerServer in 11978.928 seconds (JVM running for 11979.34)
[ERROR] 2020-04-16 13:51:01.112 org.apache.dolphinscheduler.common.zk.ZookeeperOperator:[156] - isExisted key : /dolphinscheduler/masters
java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkExists(CuratorFrameworkImpl.java:367)
	at org.apache.dolphinscheduler.common.zk.ZookeeperOperator.isExisted(ZookeeperOperator.java:154)
	at org.apache.dolphinscheduler.common.zk.AbstractZKClient.getActiveMasterNum(AbstractZKClient.java:216)
	at org.apache.dolphinscheduler.server.worker.WorkerServer$1.run(WorkerServer.java:185)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-04-16 13:51:01.179 com.alibaba.druid.pool.DruidDataSource:[1928] - {dataSource-1} closed
Exception in thread "Thread-2" org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
### The error may exist in org/apache/dolphinscheduler/dao/mapper/AlertMapper.java (best guess)
### The error may involve org.apache.dolphinscheduler.dao.mapper.AlertMapper.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy79.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:58)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy95.insert(Unknown Source)
	at org.apache.dolphinscheduler.dao.AlertDao.sendServerStopedAlert(AlertDao.java:108)
	at org.apache.dolphinscheduler.server.worker.WorkerServer$1.run(WorkerServer.java:186)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
### The error may exist in org/apache/dolphinscheduler/dao/mapper/AlertMapper.java (best guess)
### The error may involve org.apache.dolphinscheduler.dao.mapper.AlertMapper.insert
### The error occurred while executing an update
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 8 more
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:93)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doUpdate(MybatisSimpleExecutor.java:53)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 14 more
Caused by: com.alibaba.druid.pool.DataSourceDisableException
	at com.alibaba.druid.pool.DruidDataSource.pollLast(DruidDataSource.java:2057)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1537)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1326)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1306)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1296)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	... 22 more
```

**To Reproduce**
Zookeeper 3.4.14 version.

**Expected behavior**
Worker server should not be shutdown.

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by elitecodegroovy** [comment]
It has been fixed by setting the `zookeeper.session.timeout`

**Comment by elitecodegroovy** [comment]
Closed!
