### ISSUE TITLE
logger-server start error

### ISSUE THREAD

**Issue by gumupaier** [apache/incubator-dolphinscheduler#2530]
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Exception in thread "main" java.lang.IllegalArgumentException: port out of range:-1
        at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:188)
        at java.net.InetSocketAddress.<init>(InetSocketAddress.java:166)
        at io.grpc.netty.NettyServerBuilder.<init>(NettyServerBuilder.java:115)
        at io.grpc.netty.NettyServerBuilder.forPort(NettyServerBuilder.java:99)
        at io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:39)
        at io.grpc.netty.NettyServerProvider.builderForPort(NettyServerProvider.java:24)
        at io.grpc.ServerBuilder.forPort(ServerBuilder.java:39)
        at org.apache.dolphinscheduler.server.rpc.LoggerServer.start(LoggerServer.java:57)
        at org.apache.dolphinscheduler.server.rpc.LoggerServer.main(LoggerServer.java:103)

**Screenshots**
![image](https://user-images.githubusercontent.com/37896380/80304746-a2b3a280-87ea-11ea-8303-cd927b72a39c.png)
![image](https://user-images.githubusercontent.com/37896380/80304750-a9421a00-87ea-11ea-8e4e-bfe7b9148fdd.png)

**Which version of Dolphin Scheduler:**
 -[1.2.1]

**Comment by gumupaier** [comment]
I guess it may be due to the port being occupied

but the port 50051 is free

**Comment by gumupaier** [comment]
![image](https://user-images.githubusercontent.com/37896380/80304819-27062580-87eb-11ea-8672-9e0d7b8364a2.png)

**Comment by gumupaier** [comment]
@qiaozhanwei Tried many times, will have this problem, should belong to bug

**Comment by gumupaier** [comment]
Start the way

`docker pull ww1516123/incubator-dolphinscheduler
docker run -d --name incubator-dolphinscheduler -p 8888:8888 ww1516123/incubator-dolphinscheduler`

@ww1516123

**Comment by ww1516123** [comment]
> Start the way
> 
> `docker pull ww1516123/incubator-dolphinscheduler
> 
> docker run -d --name incubator-dolphinscheduler -p 8888:8888 ww1516123/incubator-dolphinscheduler`
> 
> @ww1516123

modify 
**conf/common.properties**
add 
```
# logger server rpc port
loggerserver.rpc.port=50051
```
and 
`docker run   -v ./common.properties:/opt/dolphinscheduler/conf/common.properties`

**Comment by gumupaier** [comment]
thank you, the docker hub image should be update

the problem has been solved
