### ISSUE TITLE
File management failed to add resources（文件管理添加资源失败）

### ISSUE THREAD

**Issue by moranrr** [apache/incubator-dolphinscheduler#262]
Our Hadoop cluster has kerberos enabled, creating resources in the File Management, Create Resource menu fails:
```
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        At org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:687)
        At java.security.AccessController.doPrivileged(Native Method)
        At javax.security.auth.Subject.doAs(Subject.java:422)
        At org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        At org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
        At org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:737)
        At org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        At org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        At org.apache.hadoop.ipc.Client.call(Client.java:1451)
        ... 83 common frames omitted
Caused by: javax.security.sasl.SaslException: GSS initiate failed
        At com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
        At org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:414)
        At org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        At org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        At org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
        At org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
        At java.security.AccessController.doPrivileged(Native Method)
        At javax.security.auth.Subject.doAs(Subject.java:422)
        At org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        At org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        ... 86 common frames omitted
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        At sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
        At sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        At sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        At sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        At sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        At sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        At com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
        ... 95 common frames omitted
```
There is no place to add kerberos certification.

---
我们的hadoop集群启用了kerberos，在文件管理，创建资源菜单中创建资源失败：
```
Caused by: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
        at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:687)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:650)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:737)
        at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
        at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
        at org.apache.hadoop.ipc.Client.call(Client.java:1451)
        ... 83 common frames omitted
Caused by: javax.security.sasl.SaslException: GSS initiate failed
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
        at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:414)
        at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:560)
        at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:375)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:729)
        at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:725)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:725)
        ... 86 common frames omitted
Caused by: org.ietf.jgss.GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
        ... 95 common frames omitted
```
没有添加kerberos认证的地方。

**Comment by qiaozhanwei** [comment]
启动用户kerberos中认证了吗？
资源上传调用的是hadoop api，
还有一个就是租户也是需要在kerberos认证的，否则也通不过。我们是通过sudo -u 租户 sh /xxx.command方式调用的

**Comment by moranrr** [comment]
> 启动用户kerberos中认证了吗？
> 资源上传调用的是hadoop api，
> 还有一个就是租户也是需要在kerberos认证的，否则也通不过。我们是通过sudo -u 租户 sh /xxx.command方式调用的

你的意思是需要在每个Worker的服务器上手动维护登录用户的kerberos的Ticket？

**Comment by dailidong** [comment]
has it issue already solved? it has been opened for a long time, I will close it , if you have new reply , please reopen it
