### ISSUE TITLE
Task manually triggers buildackcommand method setlogpath to throw NullPointerException exception

### ISSUE THREAD

**Issue by WeiYe-Jing** [apache/incubator-dolphinscheduler#2646]
I download the code for the dev branch, modify the data source configuration, start the project and run the task. The working server threw the following exception. I haven't made any changes to the logback-worker.xml file. Please help me to see what the problem is? Thanks.

![image](https://user-images.githubusercontent.com/33245094/81425053-72c0b380-9189-11ea-993a-6b3c02052761.png)

java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.getTaskLogPath(TaskExecuteProcessor.java:123) ~[classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.buildAckCommand(TaskExecuteProcessor.java:146) ~[classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.doAck(TaskExecuteProcessor.java:111) ~[classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:104) ~[classes/:na]
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:118) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by samz406** [comment]
add VM options as follow try try

`-Dspring.profiles.active=worker -Dlogging.config="dolphinscheduler-server/src/main/resources/logback-worker.xml"`


![image](https://user-images.githubusercontent.com/3055810/81459365-1b930100-91d2-11ea-9ea4-6e2022cbb8d4.png)

**Comment by WeiYe-Jing** [comment]
Thank you very much. After adding VM options, the problem was solved.
