### ISSUE TITLE
打rpm包报错

### ISSUE THREAD

**Issue by lijufeng2016** [apache/incubator-dolphinscheduler#2690]
[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:attached-rpm (default) on project dolphinscheduler-dist: Unable to copy files for packaging: You must set at least one file. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:attached-rpm (default) on project dolphinscheduler-dist: Unable to copy files for packaging: You must set at least one file.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to copy files for packaging: You must set at least one file.
	at org.codehaus.mojo.rpm.FileHelper.copySource(FileHelper.java:272)
	at org.codehaus.mojo.rpm.FileHelper.processSources(FileHelper.java:485)
	at org.codehaus.mojo.rpm.FileHelper.installFiles(FileHelper.java:133)
	at org.codehaus.mojo.rpm.AbstractRPMMojo.execute(AbstractRPMMojo.java:768)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: org.codehaus.plexus.archiver.ArchiverException: You must set at least one file.
	at org.codehaus.plexus.archiver.dir.DirectoryArchiver.execute(DirectoryArchiver.java:52)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:965)
	at org.codehaus.mojo.rpm.FileHelper.copySource(FileHelper.java:254)
	... 24 more

**Comment by dailidong** [comment]
which version?
@githubzhangchunyang  could you answer this question?

**Comment by lijufeng2016** [comment]
> which version?
> @githubzhangchunyang could you answer this question?

1.2.1 and 1.3.0

**Comment by githubzhangchunyang** [comment]
Configuration is available in the RPM plug-in： 
<source>
                                <location>
                                    ${basedir}/../dolphinscheduler-ui/dist
                                </location>
                                <includes>
                                    <include>**/*.*</include>
                                </includes>
                            </source>
So the directory dolphinscheduler-ui/dist is required 
But it not exist now no matter 1.2.1 or 1.3.o

**Comment by lijufeng2016** [comment]
> Configuration is available in the RPM plug-in：
> 
> ${basedir}/../dolphinscheduler-ui/dist **/*.* So the directory dolphinscheduler-ui/dist is required But it not exist now no matter 1.2.1 or 1.3.o

i make this directory still shows this issue

**Comment by githubzhangchunyang** [comment]
Execute the command ```mvn -U clean install  -Prpmbuild  -Dmaven.test.skip=true -X'``` at the root of the project
 I have tested in branch dev-1.3.0 and it worked,but  when intalling rpm package throw err 
```
错误：依赖检测失败：
 osgi(org.eclipse.core.resources) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
 osgi(org.eclipse.core.runtime) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
 osgi(org.eclipse.text) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
``` 
You can use the installation command below to temporarily resolve the problem
``` rpm -ivh apache-dolphinscheduler-incubating-1.2.1-1.noarch.rpm --nodeps --force```

A solution has been found and the code is being changed

**Comment by lijufeng2016** [comment]
> Execute the command `mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X'` at the root of the project
> I have tested in branch dev-1.3.0 and it worked,but when intalling rpm package throw err
> 
> ```
> 错误：依赖检测失败：
>  osgi(org.eclipse.core.resources) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
>  osgi(org.eclipse.core.runtime) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
>  osgi(org.eclipse.text) 被 apache-dolphinscheduler-incubating-1.2.1-1.noarch 需要
> ```
> 
> You can use the installation command below to temporarily resolve the problem
> ` rpm -ivh apache-dolphinscheduler-incubating-1.2.1-1.noarch.rpm --nodeps --force`
> 
> A solution has been found and the code is being changed

`mvn -U clean install -Prpmbuild -Dmaven.test.skip=true -X`就是执行这条报的错

**Comment by lgcareer** [comment]
Hi,I tested it on the branch dev-1.3.0,It runs successfully when execute `mvn -U clean install -Prpmbuild -Dmaven.test.skip=true` under the root directory of the project.
