### ISSUE TITLE
[BUG] Table 't_ds_worker_group' doesn't exist when init ds-1.3.0 db metadata

### ISSUE THREAD

**Issue by Eights-Li** [apache/incubator-dolphinscheduler#2835]
**Describe the bug**
dev-1.3.0
exec CreateDolphinScheduler to init db metadata will report the error: 
Table 'dolphinscheduler.t_ds_worker_group' doesn't exist

**To Reproduce**
the error : 
12:51:03.091 [main] ERROR org.apache.dolphinscheduler.dao.upgrade.WorkerGroupDao - 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'dolphinscheduler.t_ds_worker_group' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
	at com.mysql.jdbc.Util.getInstance(Util.java:360)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.apache.dolphinscheduler.dao.upgrade.WorkerGroupDao.queryAllOldWorkerGroup(WorkerGroupDao.java:48)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.updateProcessDefinitionJsonWorkerGroup(UpgradeDao.java:275)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.upgradeDolphinScheduler(UpgradeDao.java:262)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:119)
	at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:40)

**Which version of Dolphin Scheduler:**
 -[dev-1.3.0]

**Comment by Eights-Li** [comment]
i will fix it

**Comment by Eights-Li** [comment]
fixed
