### ISSUE TITLE
[QUESTION] Run Loggerserver  throw new IllegalArgumentException at checkMagic()

### ISSUE THREAD

**Issue by torysuper** [apache/incubator-dolphinscheduler#2900]
**Describe the question**
there is an Exception when i run LoggerServer(org.apache.dolphinscheduler.server.log),
See the log below for details;
it throw Exception from checkMagic();
can u help me,I spent too much time fix it,but still not solve
![image](https://user-images.githubusercontent.com/24407857/83739861-b6bfaf00-a688-11ea-958c-5bd9249f9edd.png)

**Which version of DolphinScheduler:**
 -[dev-1.3.0]

**Additional context**
17:16:31.747 [NettyServerWorkerThread_1] ERROR org.apache.dolphinscheduler.remote.handler.NettyServerHandler - exceptionCaught : java.lang.IllegalArgumentException: illegal packet [magic]80
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: illegal packet [magic]80
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: illegal packet [magic]80
	at org.apache.dolphinscheduler.remote.codec.NettyDecoder.checkMagic(NettyDecoder.java:99)
	at org.apache.dolphinscheduler.remote.codec.NettyDecoder.decode(NettyDecoder.java:53)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	... 15 common frames omitted

**Comment by torysuper** [comment]
and i cant understand the fun of 'checkMagic()',who can tell me

**Comment by xingchun-chen** [comment]
Can you describe the specific reproduction steps

**Comment by iceblue510** [comment]
> Can you describe the specific reproduction steps

我这也是这个问题。没有做特别的操作，查看了下端口，一直间断性的有explorer。exe发消息好像

**Comment by Technoboy-** [comment]
Hi, sorry for late reply. Log client will connect log server with 50051 port. If the port binds by other process, the log request can send out, but response will be checked by the log client. DS defines it's self binary protocol , and if the response is not valid, it will throw the exception you see, and the channel will close immediately. 
So, if you meet the same issue next time, try to find the process that bind the port(50051), and kill it. then restart the log server.

**Comment by gabrywu** [comment]
@torysuper If you do what as @Technoboy-  tells you, can you resolve your problem? If can, maybe this issue can be closed

**Comment by torysuper** [comment]
i fix it with change Log client port(50051) to 50059,
not only 50059,u can change port to any nonconflict port

**Comment by torysuper** [comment]
> Hi, sorry for late reply. Log client will connect log server with 50051 port. If the port binds by other process, the log request can send out, but response will be checked by the log client. DS defines it's self binary protocol , and if the response is not valid, it will throw the exception you see, and the channel will close immediately.
> So, if you meet the same issue next time, try to find the process that bind the port(50051), and kill it. then restart the log server.
thx!
but how to find the process that bind the port(50051)  with win10,
i try my best but cant find it
