### ISSUE TITLE
[BUG] bug title 1.3.0的api服务启动失败

### ISSUE THREAD

**Issue by Heltman** [apache/incubator-dolphinscheduler#2928]
我下载了1.3.0然后编译之后修改配置进行安装，然后发现啊皮服务启动失败，报了空指针异常，请问这个1.3.0是还不能使用吗？

下面是错误信息
[INFO] 2020-06-09 10:40:35.131 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2020-06-09 10:40:35.152 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[INFO] 2020-06-09 10:40:35.221 org.apache.dolphinscheduler.remote.NettyRemotingClient:[376] - netty client closed
[INFO] 2020-06-09 10:40:35.222 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed
[INFO] 2020-06-09 10:40:35.226 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-06-09 10:40:35.228 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[WARN] 2020-06-09 10:40:35.230 org.eclipse.jetty.servlet.ServletHolder:[461] - 
java.lang.NullPointerException: null
        at org.apache.jasper.servlet.JspServlet.destroy(JspServlet.java:410)
        at org.eclipse.jetty.servlet.ServletHolder.destroyInstance(ServletHolder.java:486)
        at org.eclipse.jetty.servlet.ServletHolder.doStop(ServletHolder.java:457)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:288)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
        at org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:381)
        at org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:457)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
 at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
        at org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:512)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
        at org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:932)
        at org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:375)
        at org.eclipse.jetty.webapp.WebAppContext.stopWebapp(WebAppContext.java:1503)
        at org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1467)
        at org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1009)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:288)
        at org.eclipse.jetty.webapp.WebAppContext.doStop(WebAppContext.java:569)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:149)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:170)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:124)
        at org.eclipse.jetty.server.Server.doStop(Server.java:461)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89)
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.stop(JettyWebServer.java:237)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.stopAndReleaseWebServer(ServletWebServerApplicationContext.java:320)
at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onClose(ServletWebServerApplicationContext.java:173)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1032)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:975)
        at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:834)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36)
[INFO] 2020-06-09 10:40:35.231 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@422ad5e2{application,/dolphinscheduler,[file:///tmp/jetty-docbase.6503539574314088320.12345/, jar:file:/opt/dolphinscheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources, jar:file:/opt/dolphinscheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}

**Comment by dailidong** [comment]
this mail may be help you : 
https://lists.apache.org/thread.html/r2d94500dd974c8acbafe3b5fca21182b5a50ea6b62ff962d8d4237a8%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by Heltman** [comment]
> this mail may be help you :
> https://lists.apache.org/thread.html/r2d94500dd974c8acbafe3b5fca21182b5a50ea6b62ff962d8d4237a8%40%3Cdev.dolphinscheduler.apache.org%3E

Thanks!

**Comment by gabrywu** [comment]
@Heltman Is your problem resolved ? If is , please close this issue
