### ISSUE TITLE
java.util.NoSuchElementException: 'task.record.flag' doesn't map to an existing object

### ISSUE THREAD

**Issue by wsxwsxwsx** [apache/incubator-dolphinscheduler#2935]
使用1.2.1官方提供的tar包直接进行安装，运行调度任务后，经常出现任务运行失败，但是日志显示正常的问题，查看数据也都正常落库。work报错如下：[ERROR] 2020-06-09 15:58:43.995 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[153] - task scheduler failure
java.util.NoSuchElementException: 'task.record.flag' doesn't map to an existing object
	at org.apache.commons.configuration.AbstractConfiguration.getBoolean(AbstractConfiguration.java:644)
	at org.apache.dolphinscheduler.dao.TaskRecordDao.getTaskRecordFlag(TaskRecordDao.java:64)
	at org.apache.dolphinscheduler.server.worker.task.AbstractTask.after(AbstractTask.java:134)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:150)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-06-09 15:58:43.995  - [taskAppId=TASK-4-330-5535]:[262] - cancel process: 17728
[INFO] 2020-06-09 15:58:44.000 org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread:[161] - task instance id : 5535,task final status : SUCCESS

**Comment by wsxwsxwsx** [comment]
经过一天的测试，目前而言，一直成功的任务会出现失败情况，一直失败的任务也会成功，没有规律可言。

**Comment by dailidong** [comment]
your title is different with your description? 
does it describe the same topic?

**Comment by dailidong** [comment]
please keep task.record.flag as default value(false), don't change it, this config is just used for data quality later, it's not ready, so keep default value is right choice

**Comment by dailidong** [comment]
if DolphinScheduler system works fine, it will not throw exception info in the runtime log, so if some exception info found, please check why

**Comment by chengshiwen** [comment]
Close since no updates for long time
