### ISSUE TITLE
[BUG] no email sent when query SQL has no result

### ISSUE THREAD

**Issue by gabrywu** [apache/incubator-dolphinscheduler#2983]
**Describe the bug**

no email sent when query SQL has no result

**To Reproduce**

- Create an email task to execute Query SQL which return empty result.

**Expected behavior**

An email with empty body should be sent.

**Which version of Dolphin Scheduler:**
 - [1.2.0, ]

**Requirement or improvement**
- An email should be sent for Query SQL ,no matter whether it has result or not .

**Comment by Jops-data** [comment]
Can I send the result of querying hive table with SQL node by email? Did you meet me when I sent it wrong?
 - send mail failed!
java.lang.RuntimeException: send mail failed!
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.sendAttachment(SqlTask.java:429)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:331)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:194)
	at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by gabrywu** [comment]
> Can I send the result of querying hive table with SQL node by email? Did you meet me when I sent it wrong?
> 
> * send mail failed!
>   java.lang.RuntimeException: send mail failed!
>   at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.sendAttachment(SqlTask.java:429)
>   at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:331)
>   at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:194)
>   at org.apache.dolphinscheduler.server.worker.runner.TaskScheduleThread.run(TaskScheduleThread.java:147)
>   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>   at java.lang.Thread.run(Thread.java:748)

@Jops-data  I already see your questions in another issue, so don't ask the same questions again

**Comment by gabrywu** [comment]
@dailidong @qiaozhanwei @lgcareer Hi bros, could you join to discuss about this issue ?
