### ISSUE TITLE
[BUG] Restart Ambari report an error: duplicate key: DOLPHIN_ALERT

### ISSUE THREAD

**Issue by Erik-ly** [apache/incubator-dolphinscheduler#2991]
Description：
After I replaced the common-service file in Ambari, restarting Ambari failed and the log showed:
```
2020-06-06 09:57:26,984 ERROR [main] AmbariServer:1116 - Failed to run the Ambari Server
org.apache.ambari.server.AmbariException: Could not read the alert definition file
	at org.apache.ambari.server.state.alert.AlertDefinitionFactory.getAlertDefinitions(AlertDefinitionFactory.java:103)
	at org.apache.ambari.server.api.services.AmbariMetaInfo.getAlertDefinitions(AmbariMetaInfo.java:1036)
	at org.apache.ambari.server.api.services.AmbariMetaInfo.reconcileAlertDefinitions(AmbariMetaInfo.java:1133)
	at org.apache.ambari.server.api.services.AmbariMetaInfo.reconcileAlertDefinitions(AmbariMetaInfo.java:1086)
	at org.apache.ambari.server.controller.AmbariServer.run(AmbariServer.java:538)
	at org.apache.ambari.server.controller.AmbariServer.main(AmbariServer.java:1110)
Cased by: org.apache.ambari.server.AmbariException: Could not read alert definitions
	at org.apache.ambari.server.state.alert.AlertDefinitionFactory.getAlertDefinitions(AlertDefinitionFactory.java:137)
	at org.apache.ambari.server.state.alert.AlertDefinitionFactory.getAlertDefinitions(AlertDefinitionFactory.java:99)
	... 5 more
Caused by: com.google.gson.JsonSyntaxException: duplicate key: DOLPHIN_ALERT
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:191)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:188)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:146)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at org.apache.ambari.server.state.alert.AlertDefinitionFactory.getAlertDefinitions(AlertDefinitionFactory.java:134)
	... 6 more
```

version: 
1.3.0-release

**Comment by Erik-ly** [comment]
fix this bug: https://github.com/apache/incubator-dolphinscheduler/commit/eef397675b72ad894b08045305435e0ef5946f7e
