### ISSUE TITLE
[BUG] I downloaded 1.3.0 and modified the configuration for installation after compiling. Then I found that the API service failed to start. The log is below

### ISSUE THREAD

**Issue by cailiming1994** [apache/incubator-dolphinscheduler#3036]
[INFO] 2020-06-22 15:26:13.902 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-06-22 15:26:14.448 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2020-06-22 15:26:14.526 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: queryResourceListUsingGET_1
[INFO] 2020-06-22 15:26:14.718 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
15:26:14.747 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoClassDefFoundError: org/mortbay/log/Log
        at com.sun.org.apache.commons.logging.JettyLog.<init>(JettyLog.java:36) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at com.sun.org.apache.commons.logging.LogFactory.getLog(LogFactory.java:35) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at org.apache.jasper.servlet.JspServlet.<clinit>(JspServlet.java:116) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_162]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_162]
        at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2649) ~[jetty-server-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1366) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1299) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:649) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_162]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:1.8.0_162]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743) ~[?:1.8.0_162]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742) ~[?:1.8.0_162]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_162]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36) [dolphinscheduler-api-1.3.0.jar:1.3.0]
Caused by: java.lang.ClassNotFoundException: org.mortbay.log.Log
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_162]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_162]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
        ... 35 more
[INFO] 2020-06-22 15:26:14.776 org.apache.dolphinscheduler.remote.NettyRemotingClient:[376] - netty client closed
[INFO] 2020-06-22 15:26:14.777 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed
[INFO] 2020-06-22 15:26:14.782 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-06-22 15:26:14.785 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2020-06-22 15:26:14.786 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@373052b5{application,/dolphinscheduler,[file:///tmp/jetty-docbase.5362881742322523107.12345/, jar:file:/apps/xinsight/tss/backend/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/apps/xinsight/tss/backend/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}

**Comment by yangyichao-mango** [comment]
Hi

Please change the title to english, Thx.
Can you check the lib of jetty-util-6.1.xx.jar.

**Comment by cailiming1994** [comment]
ok，thank you!

**Comment by cailiming1994** [comment]
because of our hadoop3.2 version too latest , so  jetty-util-6.1.xx.jar  conflict
