### ISSUE TITLE
Exception in the sqoop task in version 1.2.1

### ISSUE THREAD

**Issue by 1findyou** [apache/incubator-dolphinscheduler#3167]
i write the sqoop command in the shell, then call the shell, but a exception occures:
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/mapred/JobConf
		at org.apache.sqoop.orm.CompilationManager.findHadoopJars(CompilationManager.java:113)
		at org.apache.sqoop.orm.CompilationManager.compile(CompilationManager.java:146)
		at org.apache.sqoop.tool.CodeGenTool.generateORM(CodeGenTool.java:108)
		at org.apache.sqoop.tool.ImportTool.importTable(ImportTool.java:478)
		at org.apache.sqoop.tool.ImportTool.run(ImportTool.java:605)
		at org.apache.sqoop.Sqoop.run(Sqoop.java:143)
		at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
		at org.apache.sqoop.Sqoop.runSqoop(Sqoop.java:179)
		at org.apache.sqoop.Sqoop.runTool(Sqoop.java:218)
		at org.apache.sqoop.Sqoop.runTool(Sqoop.java:227)
		at org.apache.sqoop.Sqoop.main(Sqoop.java:236)
	Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapred.JobConf
		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 11 more
i have done i can, but can't solve it.

**Comment by BoYiZhang** [comment]
It seems to be an environmental problem , lacking jar packages;
You can submit the sqoop task on the command line to see if it reports an error.

**Comment by 1findyou** [comment]
thanks, i have another problem,  the worker-server and worker-servers are always affline, there are no special exception in the log, what can i do now?

**Comment by BoYiZhang** [comment]
A physical machine can only start one worker server service

**Comment by 1findyou** [comment]
so i can't run a master-server and a worker-server together in one physical machine?

**Comment by BoYiZhang** [comment]
master server and a worker server can be deployed on the same physical machine

**Comment by BoYiZhang** [comment]
You can view the logs under the logs directory

**Comment by 1findyou** [comment]
i find that master and worker usually lost connection with zookeeper. but zk is fine

**Comment by yangyichao-mango** [comment]
> i find that master and worker usually lost connection with zookeeper. but zk is fine

Hi,
Can you describe the exception when lost connection with zookeeper.

**Comment by 1findyou** [comment]
ok.  Opening socket connection to server bigdata1/192.168.221.4:2181. Will not attempt to authenticate using SASL (unknown error)

**Comment by 1findyou** [comment]
[INFO] 2020-07-10 11:46:42.980 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: SUSPENDED
[INFO] 2020-07-10 11:46:43.154 org.apache.zookeeper.ClientCnxn:[1025] - Opening socket connection to server bigdata1/192.168.221.4:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2020-07-10 11:46:43.155 org.apache.zookeeper.ClientCnxn:[879] - Socket connection established to bigdata1/192.168.221.4:2181, initiating session
[INFO] 2020-07-10 11:46:43.159 org.apache.zookeeper.ClientCnxn:[1299] - Session establishment complete on server bigdata1/192.168.221.4:2181, sessionid = 0x37336d440770001, negotiated timeout = 4000
[INFO] 2020-07-10 11:46:43.159 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: RECONNECTED
[WARN] 2020-07-10 11:46:43.867 org.apache.zookeeper.ClientCnxn:[1108] - Client session timed out, have not heard from server in 2666ms for sessionid 0x17336d449470001
[INFO] 2020-07-10 11:46:43.868 org.apache.zookeeper.ClientCnxn:[1156] - Client session timed out, have not heard from server in 2666ms for sessionid 0x17336d449470001, closing socket connection and attempting reconnect

**Comment by 1findyou** [comment]
above is the exception in the log, i have tried to solve it, but didn't work

**Comment by xingchun-chen** [comment]
Whether your problem has been resolved?
