### ISSUE TITLE
[Bug][api-server] ClassCastException: AppClassLoader cannot be cast to class java.net.URLClassLoader

### ISSUE THREAD

**Issue by hsupu** [apache/incubator-dolphinscheduler#3233]
*For better global communication, please give priority to using English description, thx! *

**Which version of Dolphin Scheduler:**
1.3.1

**Describe the bug**
Just started the api-server, logs show as follows:

```
[WARN] 2020-07-17 10:17:17.231 org.eclipse.jetty.server.handler.ContextHandler.application:[2355] - unavailable
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:174)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
	at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36)
```

I found [an explaination on stackoverflow][1]. It shows that JDK 9 has a breaking change here.

[1]: https://stackoverflow.com/questions/39739075/hive-shell-not-loading/41637409#41637409

**Requirement or improvement**
Please fix this to make DS compatible with modern JDK. Thanks!

**Comment by CalvinKirs** [comment]
I will finish it.

**Comment by dailidong** [comment]
> I will finish it.

any progress？ @CalvinKirs

**Comment by CalvinKirs** [comment]
> > I will finish it.
> 
> any progress？ @CalvinKirs

I will finish it as soon as possible

**Comment by dailidong** [comment]
any progress？

**Comment by set-daemon** [comment]
build base on 1.3.3-release, the same problem.
