### ISSUE TITLE
[Bug][Module Name] Bug title dolphinscheduler keytab认证bug

### ISSUE THREAD

**Issue by wentaowua** [apache/incubator-dolphinscheduler#3273]
[INFO] 2020-07-22 13:59:04.784  - [taskAppId=TASK-22-93-102]:[415] - find app id: application_1595373507922_23374
[ERROR] 2020-07-22 13:59:04.942 org.apache.dolphinscheduler.common.utils.HadoopUtils:[172] - Can't get Kerberos realm
java.lang.IllegalArgumentException: Can't get Kerberos realm
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:276)
	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:312)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.init(HadoopUtils.java:123)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:81)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:54)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:71)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:68)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getInstance(HadoopUtils.java:87)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:95)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:84)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
	... 25 common frames omitted
Caused by: sun.security.krb5.KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
	... 31 common frames omitted
[ERROR] 2020-07-22 13:59:04.944 org.apache.dolphinscheduler.common.utils.HadoopUtils:[102] - null
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.initHdfsPath(HadoopUtils.java:98)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:82)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:54)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:71)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:68)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getInstance(HadoopUtils.java:87)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:95)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhuangchong** [comment]
What version is this?

Which specific function？

**Comment by wuwentao515** [comment]
已解决

**Comment by xingchun-chen** [comment]
Can you write the solution , and close the issue
