### ISSUE TITLE
[Question] java.lang.IllegalArgumentException: Can't get Kerberos realm

### ISSUE THREAD

**Issue by wuwentao515** [apache/incubator-dolphinscheduler#3274]
INFO] 2020-07-22 15:13:08.169  - [taskAppId=TASK-22-94-103]:[415] - find app id: application_1595373507922_25783
[ERROR] 2020-07-22 15:13:08.328 org.apache.dolphinscheduler.common.utils.HadoopUtils:[172] - Can't get Kerberos realm
java.lang.IllegalArgumentException: Can't get Kerberos realm
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:65)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:276)
	at org.apache.hadoop.security.UserGroupInformation.setConfiguration(UserGroupInformation.java:312)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.init(HadoopUtils.java:123)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:81)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:54)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:71)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:68)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getInstance(HadoopUtils.java:87)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:95)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.security.authentication.util.KerberosUtil.getDefaultRealm(KerberosUtil.java:84)
	at org.apache.hadoop.security.HadoopKerberosName.setConfiguration(HadoopKerberosName.java:63)
	... 25 common frames omitted
Caused by: sun.security.krb5.KrbException: Cannot locate default realm
	at sun.security.krb5.Config.getDefaultRealm(Config.java:1029)
	... 31 common frames omitted
[ERROR] 2020-07-22 15:13:08.330 org.apache.dolphinscheduler.common.utils.HadoopUtils:[102] - null
java.lang.NullPointerException: null
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.initHdfsPath(HadoopUtils.java:98)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:82)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.<init>(HadoopUtils.java:54)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:71)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils$1.load(HadoopUtils.java:68)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.dolphinscheduler.common.utils.HadoopUtils.getInstance(HadoopUtils.java:87)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
	at org.apache.dolphinscheduler.server.worker.task.shell.ShellTask.handle(ShellTask.java:95)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wuwentao515** [comment]
common.properties:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/21189049/88147822-51bc1a80-cc30-11ea-94fd-e9017594e2d4.png">
install_config.conf:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/21189049/88147960-7fa15f00-cc30-11ea-89c4-fc0c34448202.png">

kerberos files path:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/21189049/88148072-a8295900-cc30-11ea-9dab-6f6310534a56.png">

**Comment by wuwentao515** [comment]
Problem solving:
配置:install_config.conf文件中
krb5ConfPath="/home/adst/data/dolphinscheduler/conf/krb5.conf"
# keytab username
keytabUserName="x x x x"
# username keytab path
keytabPath="/home/adst/data/dolphinscheduler/conf/hdfs.headless.keytab"


路径注意写installPath路径的完整路径,一开始我是使用～/data/dolphinscheduler/conf/krb5.conf，~/data/dolphinscheduler/conf/hdfs.headless.keytab然后就会报错,后来使用完整路径正确安装

**Comment by dailidong** [comment]
good job, thx
