### ISSUE TITLE
[Bug][Alert] when master or worker shutdown, alert cannot notify

### ISSUE THREAD

**Issue by JinyLeeChina** [apache/incubator-dolphinscheduler#3299]
This error log:
`[ERROR] 2020-07-22 11:00:22.209 org.apache.dolphinscheduler.common.utils.JSONUtils:[145] - parse list exception!
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character (''' (code 39)): was expecting double-quote to start field name
 at [Source: (String)"[{'type':'WORKER','host':'/dolphinscheduler/nodes/worker/hadoop/192.168.0.3:5678','event':'server down','warning level':'serious'}]"; line: 1, column: 2] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3042)
        at org.apache.dolphinscheduler.common.utils.JSONUtils.toList(JSONUtils.java:143)`

I think the reason for this is that Jackson can't parse JSON fields with single quotes.

**Comment by JinyLeeChina** [comment]
I will fix it

**Comment by felix-thinkingdata** [comment]
Json string parsing problem caused by non-standard json format.
