### ISSUE TITLE
[Bug][style] install checkstyle to IDEA failed

### ISSUE THREAD

**Issue by gaojun2048** [apache/incubator-dolphinscheduler#3432]
I pull the code of branch dev and install the checkstyle to IDEA. 

![image](https://user-images.githubusercontent.com/32193458/89615598-8fb87000-d8b9-11ea-979c-7cbedceb8e65.png)

![image](https://user-images.githubusercontent.com/32193458/89615628-9a730500-d8b9-11ea-9e3d-e33accb5ba6a.png)

And then it`s failed !

com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:147)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:198)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	... 7 more

![image](https://user-images.githubusercontent.com/32193458/89615661-ae1e6b80-d8b9-11ea-8028-2bf84a8c9f0d.png)

My OS is macos 10.15.6 
My IDEA version is 2018.2.6

**Comment by yangyichao-mango** [comment]
Need checkstyle plugin version in 8.20 or 8.22.
![image](https://user-images.githubusercontent.com/29545877/89619524-ab734480-d8c0-11ea-902c-a46635ae29f7.png)

**Comment by hsupu** [comment]
same problem on latest dev env.

- macOS 10.15.6
- IDEA 2020.2
- default checkstyle version is 8.34
