### ISSUE TITLE
[Bug][server] if resultset  has null value of some column, fastxml.jackson may ocurr exception

### ISSUE THREAD

**Issue by vayzhang** [apache/incubator-dolphinscheduler#3436]
### MyCase:
       1.  use sql task node, sql type is query;
       2. (db is oracle )config a sql, such as select *from table_t;    
            table_t has two  columns, one's name is comment, type is VARCHAR2(50),     
           another is last_updated_time , timestamp;
       3. excute the job.

![image](https://user-images.githubusercontent.com/7147384/89647035-7205fd80-d8ef-11ea-9d07-f8e6dbc6a9d1.png)

### Exception: 

java.lang.IllegalArgumentException: No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: oracle.sql.TIMESTAMP["stream"])
        at com.fasterxml.jackson.databind.ObjectMapper.valueToTree(ObjectMapper.java:2802)
        at org.apache.dolphinscheduler.common.utils.JSONUtils.toJsonNode(JSONUtils.java:67)
        at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.resultProcess(SqlTask.java:265)
        at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:232)
        at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:138)
        at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### My  Solution:
modifiy the declare ObjectMapper in  the Class "JSONUtils"  as following:
           `new ObjectMapper().configure(FAIL_ON_EMPTY_BEANS, false)          `

**Comment by yangyichao-mango** [comment]
Hi,
It will be better to avoid or adapt this situation and  in process `SqlTask.resultProcess`.
If we just configure the FAIL_ON_EMPTY_BEANS, we will not know what exception will occur in future.

**Comment by lgcareer** [comment]
@vayzhang Hi,I saw the version you said is 1.3.1,but the code pasted was not the version 1.3.1,Please correct your version,thanks.

**Comment by lgcareer** [comment]
@vayzhang Hi,I  execute the command following under oracle datasource.
1.create table student(name char(10),birthdate timestamp);
2.insert into student(name) values('zhangsan');
3.insert into student(name,birthdate) values('lisi',to_timestamp(to_char(sysdate,'yyyymmdd'),'yyyymmdd'));

![image](https://user-images.githubusercontent.com/15651066/92454769-788bdb80-f1f3-11ea-804e-bdc282b3b2d9.png)

And I tested it successful,whether you can supply your data and more detail to reproduce it?thx.
![image](https://user-images.githubusercontent.com/15651066/92454982-b688ff80-f1f3-11ea-95f9-54ea5dba2003.png)

**Comment by vayzhang** [comment]
> @vayzhang Hi,I saw the version you said is 1.3.1,but the code pasted was not the version 1.3.1,Please correct your version,thanks.

I'm so sorry for mistaking this  issue, may be I checkout the dev branch(dev-131) at that time and do not merge correctly with the branch(1.3.1 R).
the code is different between dev-131 and 1.3.1 R, so please close this issue.
