### ISSUE TITLE
DolphinScheduler 上启动Flink

### ISSUE THREAD

**Issue by islandgit** [apache/incubator-dolphinscheduler#3456]
在DolphinScheduler创建完工作流，并指定完JAR，在运行时总出现找不到JAR的情况
	org.apache.flink.client.cli.CliArgsException: Could not build the program from JAR file.
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:200)
		at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:893)
		at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:966)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1875)
		at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
		at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:966)
	Caused by: java.io.FileNotFoundException: JAR file does not exist: -yn
		at org.apache.flink.client.cli.CliFrontend.getJarFile(CliFrontend.java:717)
[INFO] 2020-08-10 18:00:24.569  - [taskAppId=TASK-3-20-24]:[121] -  -> 	at org.apache.flink.client.cli.CliFrontend.buildProgram(CliFrontend.java:693)
		at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:197)
		... 7 common frames omitted
	Could not build the program from JAR file.

**Comment by yangyichao-mango** [comment]
Hi,
Which version and please add more detail about your flink job configuration.

**Comment by islandgit** [comment]
**Describe the bug**
在Dolphin Scheduler-1.3.1版本中出现dolphin 设置Flink启动参数的BUG

**To Reproduce**
1、如果设置slot数量与taskManager数量，在执行flink 任务时会出现找不到Jar包的情况
2、在其他参数中，指定-yqu (flink on yarn 的队列名称)或者指定 -ynm （flink appName）无效

**Comment by islandgit** [comment]
Has been submitted as a BUG
