### ISSUE TITLE
ApiApplicationServer failed to start, but other Server started normally.

### ISSUE THREAD

**Issue by mandyqcx** [apache/incubator-dolphinscheduler#3570]
**Describe the bug**
ApiApplicationServer failed to start. And the dolphinscheduler-api-server-pgsrv2.out logs have following error,  
ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server

[postgres@pgsrv2 logs]$ jps
18609 LoggerServer
18657 AlertServer
18564 WorkerServer
22789 AlertServer
22742 LoggerServer
18519 MasterServer
22697 WorkerServer
9964 QuorumPeerMain
22652 MasterServer
23359 Jps

![image](https://user-images.githubusercontent.com/34437466/90869107-5825e980-e3ca-11ea-95d7-58f4e6e93a0c.png)

### The log in dolphinscheduler-api-server-pgsrv2.out is here
`Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

[INFO] 2020-08-21 15:04:15.978 org.eclipse.jetty.util.log:[193] - Logging initialized @18007ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2020-08-21 15:04:16.419 org.eclipse.jetty.server.Server:[370] - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 11.0.8+10-LTS
[INFO] 2020-08-21 15:04:16.501 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-08-21 15:04:16.616 org.eclipse.jetty.server.session:[365] - DefaultSessionIdManager workerName=node0
[INFO] 2020-08-21 15:04:16.617 org.eclipse.jetty.server.session:[370] - No SessionScavenger set, using defaults
[INFO] 2020-08-21 15:04:16.623 org.eclipse.jetty.server.session:[149] - node0 Scavenging every 600000ms
[INFO] 2020-08-21 15:04:16.637 org.eclipse.jetty.server.handler.ContextHandler:[855] - Started o.s.b.w.e.j.JettyEmbeddedWebAppContext@5ffd35dd{application,/dolphinscheduler,[file:///tmp/jetty-docbase.1884328835880379741.12345/, jar:file:/usr/local/dolphinscheduler-1.3.1/dolphinscheduler-data/bin/../lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/usr/local/dolphinscheduler-1.3.1/dolphinscheduler-data/bin/../lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],AVAILABLE}
[INFO] 2020-08-21 15:04:16.639 org.eclipse.jetty.server.Server:[407] - Started @18682ms
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.2.0 
[INFO] 2020-08-21 15:04:20.370 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[82] - zookeeper registry center init, server lists is: pgsrv2:2181.
[INFO] 2020-08-21 15:04:20.460 org.apache.curator.utils.Compatibility:[48] - Running in ZooKeeper 3.4.x compatibility mode
[INFO] 2020-08-21 15:04:20.465 org.apache.curator.utils.Compatibility:[61] - Using emulated InjectSessionExpiration
[INFO] 2020-08-21 15:04:20.519 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-08-21 15:04:20.565 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-08-21 15:04:20.597 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-08-21 15:04:20.607 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[82] - zookeeper registry center init, server lists is: pgsrv2:2181.
[INFO] 2020-08-21 15:04:20.608 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-08-21 15:04:20.612 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-08-21 15:04:20.614 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-08-21 15:04:20.626 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[43] - add listener to zk path: /dolphinscheduler
[INFO] 2020-08-21 15:04:20.830 org.apache.dolphinscheduler.service.zk.ZookeeperOperator:[82] - zookeeper registry center init, server lists is: pgsrv2:2181.
[INFO] 2020-08-21 15:04:20.831 org.apache.curator.framework.imps.CuratorFrameworkImpl:[308] - Starting
[INFO] 2020-08-21 15:04:20.834 org.apache.curator.framework.imps.CuratorFrameworkImpl:[356] - Default schema
[INFO] 2020-08-21 15:04:20.839 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-08-21 15:04:20.840 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[43] - add listener to zk path: /dolphinscheduler
[INFO] 2020-08-21 15:04:23.361 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2020-08-21 15:04:23.441 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2020-08-21 15:04:23.627 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2020-08-21 15:04:24.323 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2020-08-21 15:04:24.457 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: queryResourceListUsingGET_1
[INFO] 2020-08-21 15:04:24.657 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2020-08-21 15:04:24.688 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[WARN] 2020-08-21 15:04:24.715 org.eclipse.jetty.server.handler.ContextHandler.application:[2355] - unavailable
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:174)
        at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672)
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429)
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46)
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36)
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221)
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36)
[INFO] 2020-08-21 15:04:24.717 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2020-08-21 15:04:24.719 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2020-08-21 15:04:24.720 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@5ffd35dd{application,/dolphinscheduler,[file:///tmp/jetty-docbase.1884328835880379741.12345/, jar:file:/usr/local/dolphinscheduler-1.3.1/dolphinscheduler-data/bin/../lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/usr/local/dolphinscheduler-1.3.1/dolphinscheduler-data/bin/../lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}
15:04:24.730 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty server
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:168) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:311) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.apache.dolphinscheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:36) [dolphinscheduler-api-1.3.1.jar:1.3.1]
Caused by: javax.servlet.ServletException: jsp@19c47==org.apache.jasper.servlet.JspServlet,jsp=null,order=3,inst=false,async=true
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:693) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        ... 10 more
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:174) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:672) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:429) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744) ~[jetty-servlet-9.4.14.v20181114.jar:9.4.14.v20181114]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext$JettyEmbeddedServletHandler.deferredInitialize(JettyEmbeddedWebAppContext.java:46) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyEmbeddedWebAppContext.deferredInitialize(JettyEmbeddedWebAppContext.java:36) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.handleDeferredInitialize(JettyWebServer.java:221) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.start(JettyWebServer.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        ... 10 more
[INFO] 2020-08-21 15:04:24.774 org.apache.dolphinscheduler.remote.NettyRemotingClient:[376] - netty client closed
[INFO] 2020-08-21 15:04:24.775 org.apache.dolphinscheduler.service.log.LogClientService:[59] - logger client closed`

**Which version of Dolphin Scheduler:**
 -[1.3.1]

**Which version of JDK:**
[postgres@pgsrv2 logs]$ java --version
java 11.0.8 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

I have no idea with it, please tell how to fix it.
If you need anyting more ,please let me know ,Thanks!

**Comment by yangyichao-mango** [comment]
The same with #3233 .
Tag: could be closed. @yangyichao-mango

**Comment by ooeeerrtt** [comment]
please check your port. 
api 12345     worker 1234      master 5678
maybe address already in use
