### ISSUE TITLE
[Bug][worker]  get yarn applications status from yarn server,http code return 404, get yarn applications status cause NullPointerException 

### ISSUE THREAD

**Issue by 597365581** [apache/incubator-dolphinscheduler#3645]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
[ERROR] 2020-09-02 15:37:27.040 org.apache.dolphinscheduler.common.utils.HttpUtils:[70] - http get:404 response status code is not 200!
[ERROR] 2020-09-02 15:37:27.043  - [taskAppId=TASK-5-185-263]:[388] - yarn applications: [application_1598594304061_22447]  status failed
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.common.utils.HadoopUtils.getApplicationStatus(HadoopUtils.java:415)
        at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.isSuccessOfYarnState(AbstractCommandExecutor.java:374)
        at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:218)
        at org.apache.dolphinscheduler.server.worker.task.AbstractYarnTask.handle(AbstractYarnTask.java:57)
        at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
**Which version of Dolphin Scheduler:**
 -[1.3.2]

**Comment by 597365581** [comment]
I will fix this issue

**Comment by 597365581** [comment]
yarn reurn {"RemoteException":{"exception":"NotFoundException","message":"java.lang.Exception: app with id: application_1598432328928_00222 not found","javaClassName":"org.apache.hadoop.yarn.webapp.NotFoundException"}}[root@linkkids-platform-bigdata-scripts-2-20 logs]
