### ISSUE TITLE
[Question] dolphinscheduler1.3.1 资源中心无法上传文件到本地，也无法上传文件到hdfs？？

### ISSUE THREAD

**Issue by lishiyucn** [apache/incubator-dolphinscheduler#3650]
希望能把文件上传到本地，多种格式都尝试了，页面一直报这个错误 - **创建资源错误**
我的配置

```
resource.storage.type=HDFS

# resource store on HDFS/S3 path, resource file will store to this hadoop hdfs path, self configuration, please make sure the directory exists on hdfs and have read write permissions。"/dolphinscheduler" is recommended
resource.upload.path=/data/dolphinscheduler

# user data local directory path, please make sure the directory exists and have read write permissions
data.basedir.path=/data/dolphinscheduler
hdfs.root.user=hdfs

# if resource.storage.type=HDFS
fs.defaultFS=file:///data/dolphinscheduler

```

log error message is :
```
[INFO] 2020-09-02 09:54:50.623 org.apache.dolphinscheduler.api.controller.ResourcesController:[99] - login user admin, create resource, type: FILE, resource alias: asdf, desc: , file: -1,/
[ERROR] 2020-09-02 09:54:50.662 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 创建资源错误
java.lang.NullPointerException: null
        at org.apache.dolphinscheduler.api.service.ResourcesService.createDirecotry(ResourcesService.java:484)
        at org.apache.dolphinscheduler.api.service.ResourcesService.createDirectory(ResourcesService.java:148)
        at org.apache.dolphinscheduler.api.service.ResourcesService$$FastClassBySpringCGLIB$$cfb54838.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.apache.dolphinscheduler.api.service.ResourcesService$$EnhancerBySpringCGLIB$$2371a150.createDirectory(<generated>)
        at org.apache.dolphinscheduler.api.controller.ResourcesController.createDirectory(ResourcesController.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
```

*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by dailidong** [comment]
which version do you use? 
and Did you follow the steps in the website?,  please step by step, don't skip any step

**Comment by when520** [comment]
> which version do you use?
> and Did you follow the steps in the website?, please step by step, don't skip any step

version is dolphinscheduler1.3.1   the title contains version info, I  install the dolphin by the 1.3.1 doc

**Comment by yy0812** [comment]
Looking at the 1.3.1 resourcesService class, the null pointer error occurred because the current logged in user was in a tenant that could not be found. Have you done anything similar to manually changing the tenant ID in the database?

**Comment by yy0812** [comment]
A closer look at the code reveals that this is a BUG in version 1.3.1, which would occur if you created a resource directory using an Admin user because the admin user does not belong to any of the tenants. This problem has been solved in version 1.3.2 by adding validation. It is recommended that you create a non-admin account and switch to change the user to create the resource

**Comment by momoh2018** [comment]
1.2 版本 也有这个错误    
这个在自己搭建的情况下，没有hadoop， 随便测试下就会复现这个问题

**Comment by lishiyucn** [comment]
the admin user can't create folder and file,I login the other user can create folder and upload file.

**Comment by lishiyucn** [comment]
> which version do you use?
> and Did you follow the steps in the website?, please step by step, don't skip any step

the question title contains the dolphinscheduler version 1.3.1
