### ISSUE TITLE
What happens when the Mysql task fails?

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#3790]
用的1.3.2的版本，然后执行MySQL任务时就一直报如下错误：
[INFO] 2020-09-23 00:18:01.381  - [taskAppId=TASK-1-7-7]:[104] - Full sql parameters: SqlParameters{type='MYSQL', datasource=1, sql='select * from t_ds_user;', sqlType=0, udfs='', showType='TABLE', connParams='', title='msyql_select', receivers='dam@qq.com', receiversCc='', preStatements=[], postStatements=[]}
[INFO] 2020-09-23 00:18:01.384  - [taskAppId=TASK-1-7-7]:[105] - sql type : MYSQL, datasource : 1, sql : select * from t_ds_user; , localParams : [],udfs : ,showType : TABLE,connParams : 
[INFO] 2020-09-23 00:18:01.384  - [taskAppId=TASK-1-7-7]:[176] - SQL title : msyql_select
[INFO] 2020-09-23 00:18:01.385  - [taskAppId=TASK-1-7-7]:[499] - after replace sql , preparing : select * from t_ds_user;
[INFO] 2020-09-23 00:18:01.385  - [taskAppId=TASK-1-7-7]:[504] - Sql Params are replaced sql , parameters:
[INFO] 2020-09-23 00:18:01.385  - [taskAppId=TASK-1-7-7]:[52] - can't find udf function resource
[INFO] 2020-09-23 00:18:01.415  - [taskAppId=TASK-1-7-7]:[418] - prepare statement replace sql : com.mysql.jdbc.JDBC42PreparedStatement@76661b5c: select * from t_ds_user; 
[ERROR] 2020-09-23 00:18:16.433  - [taskAppId=TASK-1-7-7]:[242] - execute sql error
java.lang.RuntimeException: send mail failed!
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.sendAttachment(SqlTask.java:461)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.resultProcess(SqlTask.java:275)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:232)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:139)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-09-23 00:18:16.434  - [taskAppId=TASK-1-7-7]:[145] - sql task error
java.lang.RuntimeException: execute sql error
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:243)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:139)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhuangchong** [comment]
The error shows that sending mail failed, please check the configuration of receivers='dam@qq.com' and ds conf/alert.properties server mailbox

---
错误显示发送邮件失败，请检查receivers='dam@qq.com' 和 ds conf/alert.properties 服务端邮箱的配置

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by xingchun-chen** [comment]
please check the email configuration in  conf/alert.properties
![image](https://user-images.githubusercontent.com/55787491/93960156-da1f7e80-fd8b-11ea-9760-2d531e3e8a14.png)

**Comment by shiliquan** [comment]
![image](https://user-images.githubusercontent.com/42087586/93962222-dfc99400-fd8c-11ea-8f20-d5dc76f1bab4.png)
这个配置是和您上面一样的啊，只是邮件地址是测试邮件地址，并非真实存在，无法联网发送的！

**Comment by xingchun-chen** [comment]
The TLS protocol is 25, and the sender and user of the email should be a real one

**Comment by shiliquan** [comment]
好的知道了 ，感谢！
请帮我解答下hive连接源的设置相关问题（在最新问题栏有贴），谢了！

**Comment by CalvinKirs** [comment]
solved
