### ISSUE TITLE
[Bug][Ambari Plugin] Start Ambari report an error: Table 't_ds_process_definition_version' already exists

### ISSUE THREAD

**Issue by yangruochen** [apache/incubator-dolphinscheduler#3845]
Description：
I install the dolphinscheduler in Ambari, I try to start DS_Api and hit the bug :

15:48:43.481 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CALL ct_dolphin_T_t_ds_process_definition_version 
15:48:43.492 [main] ERROR org.apache.dolphinscheduler.common.utils.ScriptRunner - SQLException
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 't_ds_process_definition_version' already exists
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:829)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:729)
	at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:145)
	at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:75)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.upgradeDolphinSchedulerDDL(UpgradeDao.java:410)
	at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.upgradeDolphinScheduler(UpgradeDao.java:258)
	at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.upgradeDolphinScheduler(DolphinSchedulerManager.java:117)
	at org.apache.dolphinscheduler.dao.upgrade.shell.UpgradeDolphinScheduler.main(UpgradeDolphinScheduler.java:36)

Screenshots:

![截屏2020-09-28 下午4 12 50](https://user-images.githubusercontent.com/11856719/94407118-9c649080-01a5-11eb-8c0d-8cf9b6ba0eeb.png)

version:
dev

**Comment by yangruochen** [comment]
because of pull request #3053 , the t_ds_process_definition_version was added.
I delete upgrade-dolphinscheduler in dolphin_api_service.py, because there is upgradeDolphinScheduler in CreateDolphinScheduler.

![截屏2020-09-28 下午4 56 44](https://user-images.githubusercontent.com/11856719/94411979-cfaa1e00-01ab-11eb-898b-e350899c3903.png)

**Comment by gaojun2048** [comment]
I think the problem is in the schema file. Not here.
In order to ensure that the table structure metadata is up to date, we need to execute the upgrade-dolphinscheduler.sh script at startup. This script will automatically check the current version number and execute the corresponding upgrade sql file.

Therefore, we require that the sql file in the schema must meet the ability of repeatable execution.
In order to achieve this goal, if we need to create the table t_ds_process_definition_version, then we should use 

```
create table IF NOT EXISTS t_ds_process_definition_version;

``` 
or

```
drop table if exists t_ds_process_definition_version;
create table t_ds_process_definition_version;

```

**Comment by yangruochen** [comment]
> I think the problem is in the schema file. Not here.
> In order to ensure that the table structure metadata is up to date, we need to execute the upgrade-dolphinscheduler.sh script at startup. This script will automatically check the current version number and execute the corresponding upgrade sql file.
> 
> Therefore, we require that the sql file in the schema must meet the ability of repeatable execution.
> In order to achieve this goal, if we need to create the table t_ds_process_definition_version, then we should use
> 
> ```
> create table IF NOT EXISTS t_ds_process_definition_version;
> ```
> 
> or
> 
> ```
> drop table if exists t_ds_process_definition_version;
> create table t_ds_process_definition_version;
> ```

ok, thank you, I correct it.
