### ISSUE TITLE
[Question] publish schedule online error

### ISSUE THREAD

**Issue by 1015zhc** [apache/incubator-dolphinscheduler#3850]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the question**
A clear and concise description of what the question is.
当进行定时任务操作时，配置后点击上线，界面报错 ‘上线调度配置错误’；
![image](https://user-images.githubusercontent.com/47803280/94525431-a7cbc080-0266-11eb-8a16-0e35bd79f207.png)
![image](https://user-images.githubusercontent.com/47803280/94525607-e5304e00-0266-11eb-9262-84fa11c7c5a9.png)

**Which version of DolphinScheduler:**
 -[1.3.2]

**Additional context**
查看日志dolphinscheduler-api-server.log，报错如下:

```
[ERROR] 2020-09-29 15:04:40.082 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 上线调度配置错误
java.lang.RuntimeException: set online failure
        at org.apache.dolphinscheduler.api.service.SchedulerService.setScheduleState(SchedulerService.java:395)
        at org.apache.dolphinscheduler.api.service.SchedulerService$$FastClassBySpringCGLIB$$628050e2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.apache.dolphinscheduler.api.service.SchedulerService$$EnhancerBySpringCGLIB$$451e6cf9.setScheduleState(<generated>)
        at org.apache.dolphinscheduler.api.controller.SchedulerController.online(SchedulerController.java:183)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
```

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by qiaozhanwei** [comment]
please change title to english . thx
1，judge if master service startup
2，if started. you can see QRTZ_SCHEDULER_STATE table whether has data

**Comment by 1015zhc** [comment]
1.the table of QRTZ_SCHEDULER_STATE has data.
like this
![image](https://user-images.githubusercontent.com/47803280/94531964-d26e4700-026f-11eb-9613-e5227a378903.png)
2.master server is running.
![image](https://user-images.githubusercontent.com/47803280/94532091-ff225e80-026f-11eb-92ca-89c25616a19b.png)

**Comment by qiaozhanwei** [comment]
Install or upgrade directly ？

是直接安装的还是从别的版本升级过来的？
如果是升级过来的可能是不兼容以前的定时
如果是直接安装的，是不是你的定时表和元数据表，没有在一个db下面，你有修改quartz.properties配置信息么？
个人感觉是定时系统表应该是有问题的，如果查找不到别的原因，可以先停止master，t_ds_schedules状态设置为下线，然后把系统定时表所有数据删除，重新启动Master，重新定时上线

**Comment by 1015zhc** [comment]
> Install or upgrade directly ？
> 
> 是直接安装的还是从别的版本升级过来的？
> 如果是升级过来的可能是不兼容以前的定时
> 如果是直接安装的，是不是你的定时表和元数据表，没有在一个db下面，你有修改quartz.properties配置信息么？
> 个人感觉是定时系统表应该是有问题的，如果查找不到别的原因，可以先停止master，t_ds_schedules状态设置为下线，然后把系统定时表所有数据删除，重新启动Master，重新定时上线

是直接安装的，没有修改quartz.properties，用的同一个db(dolphinscheduler)。
好的 我试一下清理数据

**Comment by 1015zhc** [comment]
> Install or upgrade directly ？
> 
> 是直接安装的还是从别的版本升级过来的？
> 如果是升级过来的可能是不兼容以前的定时
> 如果是直接安装的，是不是你的定时表和元数据表，没有在一个db下面，你有修改quartz.properties配置信息么？
> 个人感觉是定时系统表应该是有问题的，如果查找不到别的原因，可以先停止master，t_ds_schedules状态设置为下线，然后把系统定时表所有数据删除，重新启动Master，重新定时上线

请问系统定时表是t_ds_schedules吗？还是QRTZ_SCHEDULER_STATE 呢，我试了下删除t_ds_schedules中的数据，再启动还是报错，不起作用。
当我直接设置t_ds_schedules表中的数据为上线时，可以跑脚本。

**Comment by xingchun-chen** [comment]
Has your problem been resolved? If it has been resolved, please close the issue

**Comment by glxfeng** [comment]
我也遇到了，是因为flow里的某个作业不存在或者没有上线的原因

**Comment by shmilygkd** [comment]
碰到同样问题+1，全新安装的服务在使用定时服务时就碰到该问题，希望可以帮忙解答一下，tks!

版本是2.0.0，尝试过重启服务，更换项目和工作流，都没有效果。

**Comment by Tangsonghuai** [comment]
> 碰到同样问题+1，全新安装的服务使用定时服务时就碰到该问题，希望可以帮忙解答一下，tks!
> 
> 版本是2.0.0，尝试过重启服务，更换项目和工作流，都没有效果。
h

> 碰到同样问题+1，全新安装的服务在使用定时服务时就碰到该问题，希望可以帮忙解答一下，tks!
> 
> 版本是2.0.0，尝试过重启服务，更换项目和工作流，都没有效果。

后来解决了吗
