### ISSUE TITLE
work节点运行mr程序怎么会清理客户端本地hadoop目录下的mapred临时文件？

### ISSUE THREAD

**Issue by 939598604** [apache/incubator-dolphinscheduler#3859]
[INFO] 2020-09-30 11:24:23.012  - [taskAppId=TASK-1-5-5]:[121] -  -> 20/09/30 11:24:23 INFO Configuration.deprecation: session.id is deprecated. Instead, use dfs.metrics.session-id
[INFO] 2020-09-30 11:24:23.798  - [taskAppId=TASK-1-5-5]:[121] -  -> 20/09/30 11:24:23 INFO jvm.JvmMetrics: Initializing JVM Metrics with processName=JobTracker, sessionId=
	20/09/30 11:24:23 INFO mapreduce.JobSubmitter: Cleaning up the staging area file:/data/hadoop-2.7.1/tmp/mapred/staging/test54419378/.staging/job_local54419378_0001
	ENOENT: No such file or directory
		at org.apache.hadoop.io.nativeio.NativeIO$POSIX.chmodImpl(Native Method)
		at org.apache.hadoop.io.nativeio.NativeIO$POSIX.chmod(NativeIO.java:230)
		at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:724)
		at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:502)
		at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:600)
		at org.apache.hadoop.mapreduce.JobResourceUploader.uploadFiles(JobResourceUploader.java:94)
		at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:95)
		at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:190)
		at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
		at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.security.auth.Subject.doAs(Subject.java:422)
		at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
		at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
		at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1308)
		at org.apache.hadoop.examples.WordCount.main(WordCount.java:87)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
		at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
		at org.apache.hadoop.examples.ExampleDriver.main(ExampleDriver.java:74)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
		at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by xingchun-chen** [comment]
please update the title in English

**Comment by dailidong** [comment]
this is not the behaver of DolphinScheduler,  DolphinScheduler just submit the task to Hadoop Cluster
