### ISSUE TITLE
[Question] upgrede issue [1.2.0 to 1.3.2]

### ISSUE THREAD

**Issue by zhoushigan** [apache/incubator-dolphinscheduler#3960]
[INFO] 2020-10-21 13:11:17.459 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[121] - there is not enough thread for this command: Command{id=1806838, commandType=RECOVER_WAITTING_THREAD, processDefinitionId=263, executorId=4, commandParam='{"WaittingThreadInstanceId":"1762594"}', taskDependType=TASK_POST, failureStrategy=CONTINUE, warningType=FAILURE, warningGroupId=0, scheduleTime=Wed Oct 21 13:08:00 CST 2020, startTime=Wed Oct 21 13:08:00 CST 2020, processInstancePriority=MEDIUM, updateTime=Wed Oct 21 13:11:16 CST 2020, workerGroup='default'}
[ERROR] 2020-10-21 13:11:17.459 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=122432, bodyLen=24574] due to no suitable worker , current task need to default worker group execute
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:145)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:114)
[ERROR] 2020-10-21 13:11:17.466 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=122433, bodyLen=11809] due to no suitable worker , current task need to default worker group execute
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:145)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:114)
[INFO] 2020-10-21 13:11:17.468 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 1806840, type: RECOVER_WAITTING_THREAD
[INFO] 2020-10-21 13:11:17.469 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[121] - there is not enough thread for this command: Command{id=1806840, commandType=RECOVER_WAITTING_THREAD, processDefinitionId=261, executorId=4, commandParam='{"WaittingThreadInstanceId":"1762596"}', taskDependType=TASK_POST, failureStrategy=CONTINUE, warningType=FAILURE, warningGroupId=0, scheduleTime=Wed Oct 21 13:08:00 CST 2020, startTime=Wed Oct 21 13:08:00 CST 2020, processInstancePriority=MEDIUM, updateTime=Wed Oct 21 13:11:16 CST 2020, workerGroup='default'}
[ERROR] 2020-10-21 13:11:17.473 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=122434, bodyLen=7925] due to no suitable worker , current task need to default worker group execute
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:145)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:114)
[INFO] 2020-10-21 13:11:17.479 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 1806842, type: RECOVER_WAITTING_THREAD
[ERROR] 2020-10-21 13:11:17.480 org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer:[148] - dispatch error
org.apache.dolphinscheduler.server.master.dispatch.exceptions.ExecuteException: fail to execute : Command [type=TASK_EXECUTE_REQUEST, opaque=122435, bodyLen=24574] due to no suitable worker , current task need to default worker group execute
	at org.apache.dolphinscheduler.server.master.dispatch.ExecutorDispatcher.dispatch(ExecutorDispatcher.java:87)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.dispatch(TaskPriorityQueueConsumer.java:145)
	at org.apache.dolphinscheduler.server.master.consumer.TaskPriorityQueueConsumer.run(TaskPriorityQueueConsumer.java:114)

**Comment by xingchun-chen** [comment]
According to the log: worker group has no default, you can configure worker.groups=default in conf/worker.properties, and restart the worker service

**Comment by ryze124** [comment]
I have two  masters ;
when i submit my jobs to master02, they run well;
however, when jobs  go to master01, master01 return this error.   
what's the master01's problem？
