### ISSUE TITLE
[Bug][quartz scheduler] when i use v1.3.3 create a scheduler job,it does not work

### ISSUE THREAD

**Issue by lookhua** [apache/incubator-dolphinscheduler#3984]
[ERROR] 2020-10-24 13:44:27.794 org.quartz.core.ErrorLogger:[2425] - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: ERROR: value too long for type character varying(95)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2864)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(95)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeUpdate(DruidPooledPreparedStatement.java:255)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2666)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2847)
	... 5 common frames omitted

**Comment by lookhua** [comment]
i deploy doph  in k8s , the entry_id is very long , just like this( length is 122 ,and lang than 95 ):

dolphinscheduler-fat-master-0.dolphinscheduler-fat-master-headless.bigdata-fat.svc.cluster.local16035192960901603520223639

**Comment by hermeshephaestus** [comment]
In business, you should find a way to shorten entry_id. Or you can locally change the type of database corresponding field or lengthen it. Have a try. @lookhua

**Comment by xingchun-chen** [comment]
Is your problem solved, if it is solved, please close it.thanks

**Comment by CalvinKirs** [comment]
You should solve it as @hermeshephaestus said, this is an easy problem to solve.
