### ISSUE TITLE
[Question] when shceduler want to call schedule job, then it  threw an unhandled Exception

### ISSUE THREAD

**Issue by havenBoy** [apache/incubator-dolphinscheduler#4020]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*
当定时任务执行时，会报出以下的错误
**Describe the question**
i use 'sh bin/dolphinscheduler-daemon.sh start master-server' to start three apps,but master log show like this :

[DEBUG] 2020-11-03 19:31:30.008 org.quartz.core.JobRunShell:[201] - Calling execute on job jobgroup_51.job_15
[ERROR] 2020-11-03 19:31:30.008 org.quartz.core.JobRunShell:[211] - Job jobgroup_51.job_15 threw an unhandled Exception:
java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@f316aeb has not been refreshed yet
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1096)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1126)
        at org.apache.dolphinscheduler.service.bean.SpringApplicationContext.getBean(SpringApplicationContext.java:35)
        at org.apache.dolphinscheduler.service.quartz.ProcessScheduleJob.getProcessService(ProcessScheduleJob.java:50)
        at org.apache.dolphinscheduler.service.quartz.ProcessScheduleJob.execute(ProcessScheduleJob.java:62)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Which version of DolphinScheduler:**
 -[1.3.2-preview]

**Additional context**

**Requirement or improvement**
don't konw how to make it work

**Comment by dailidong** [comment]
we don't publish 1.3.2-preview version ?  is this question on version 1.3.2 ?

**Comment by havenBoy** [comment]
yes, i have solved this problem , thx

**Comment by yanglk2010** [comment]
这个问题怎么解决吗？能说一下吗？
