### ISSUE TITLE
when execute mysql json function caused exception  :  Invalid JSON path expression

### ISSUE THREAD

**Issue by lil-winga** [apache/incubator-dolphinscheduler#4033]
execute sql error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid JSON path expression. The error is around character position 1.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2111)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:1985)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3358)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:464)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3070)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2338)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2725)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2020)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:231)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:139)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 2020-11-06 14:54:20.698  - [taskAppId=TASK-11-33-52]:[145] - sql task error
java.lang.RuntimeException: execute sql error
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:243)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:139)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/33838619/98337921-52908500-2044-11eb-99f4-0d07ebeaceb1.png)

**Comment by xingchun-chen** [comment]
please  update the title in English, thanks

**Comment by xingchun-chen** [comment]
Is the coach and category you query the value in the json string?

**Comment by lil-winga** [comment]
> Is the coach and category you query the value in the json string?

![image](https://user-images.githubusercontent.com/33838619/98350573-7e1c6b00-2056-11eb-835e-1319c9df0500.png)
![image](https://user-images.githubusercontent.com/33838619/98350655-99877600-2056-11eb-9d51-4b30f1abaf20.png)
thanks please help me

**Comment by xingchun-chen** [comment]
I can't see the picture. Can your SQL statement be queried successfully in the database?

**Comment by lil-winga** [comment]
> I can't see the picture. Can your SQL statement be queried successfully in the database?

yes, it is ,this sql SQL statement be queried successfully in the database

**Comment by xingchun-chen** [comment]
You can try to query only one JSON_EXTRACT

**Comment by lil-winga** [comment]
> You can try to query only one JSON_EXTRACT

I try  only one JSON_EXTRACT  is error 
---- 
 execute sql error
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid JSON path expression. The error is around character position 1.

![image](https://user-images.githubusercontent.com/33838619/98497925-717b5b00-2280-11eb-944a-7418b3a37e8b.png)

**Comment by xingchun-chen** [comment]
The query field value is in json format,  that is ok, but the array format will report an error. Who wants to fix this problem
![image](https://user-images.githubusercontent.com/55787491/98506904-74ce1100-2297-11eb-8860-d6241911acff.png)
![image](https://user-images.githubusercontent.com/55787491/98506920-81526980-2297-11eb-9cd7-b75ac963101f.png)

**Comment by lil-winga** [comment]
> The query field value is in json format, that is ok, but the array format will report an error. Who wants to fix this problem

i think you can fix this problem , thx

**Comment by CalvinKirs** [comment]
i will fix it

**Comment by lil-winga** [comment]
> i will fix it

oh yes ,thank you , expect
