### ISSUE TITLE
create user defeat

### ISSUE THREAD

**Issue by glaryaugus** [apache/incubator-dolphinscheduler#4044]
when i create a user or tenant,it take a problem

[ERROR] 2020-11-10 14:24:18.190 org.apache.dolphinscheduler.api.exceptions.ApiExceptionHandler:[45] - 创建用户错误
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236)
        at org.apache.dolphinscheduler.common.enums.ResUploadType.valueOf(ResUploadType.java:22)
        at org.apache.dolphinscheduler.common.utils.PropertyUtils.getResUploadStartupState(PropertyUtils.java:76)
        at org.apache.dolphinscheduler.api.service.UsersService.createUser(UsersService.java:126)
        at org.apache.dolphinscheduler.api.service.UsersService$$FastClassBySpringCGLIB$$e4fd56f5.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)

how about to deal with it,please answer in chinese

**Comment by zhuangchong** [comment]
Which version？

**Comment by glaryaugus** [comment]
done
