### ISSUE TITLE
[Question] The problem of task dependency logging in process definition

### ISSUE THREAD

**Issue by baijun** [apache/incubator-dolphinscheduler#4060]
My workflow USES dependency tasks, but I find that the dependency tasks are detected by a log file, so if the log is cleaned up it will never be finished (unless the log is patched back up), how to deal with this problem and clean up the log file periodically.

The directory in the log has been cleaned up by me, and other tasks that depend on this task cannot be performed effectively.

![image](https://user-images.githubusercontent.com/7664170/98905983-4cdce880-24f7-11eb-808c-4a95527e738e.png)

14:43:14.219 [pool-2-thread-1] INFO org.apache.dolphinscheduler.server.log.LoggerRequestProcessor - received command : Command [type=ROLL_VIEW_LOG_REQUEST, opaque=27, bodyLen=88]
14:43:14.299 [pool-2-thread-1] ERROR org.apache.dolphinscheduler.server.log.LoggerRequestProcessor - read file error
java.nio.file.NoSuchFileException: /hwdata/dolphinscheduler/logs/148/1523/12761.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.lines(Files.java:3744)
	at java.nio.file.Files.lines(Files.java:3785)
	at org.apache.dolphinscheduler.server.log.LoggerRequestProcessor.readPartFileContent(LoggerRequestProcessor.java:156)
	at org.apache.dolphinscheduler.server.log.LoggerRequestProcessor.process(LoggerRequestProcessor.java:80)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

我的工作流使用了依赖任务，但是我发现依赖任务检测时是通过日志文件的方式，那假如日志被清理后此处就永远无法完成了（除非补数，将日志重新修补回来），这个问题应该如何处理，做到定期清理日志文件。
日志里的目录已被我清理掉，之后依赖此任务的其他任务都无法有效执行了

**Comment by chengshiwen** [comment]
Close by #4272
