### ISSUE TITLE
[Bug][worker]command body parseObject error

### ISSUE THREAD

**Issue by chengpeng2015** [apache/incubator-dolphinscheduler#4125]
code:

class: DBTaskResponseProcessor
method: process
line: JSONUtils.parseObject(command.getBody(),DBTaskResponseCommand.class);
runing data: {"taskInstanceId":8,"status":7}

error details:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.remote.command.DBTaskResponseCommand` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"taskInstanceId":6,"status":7}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004) ~[jackson-databind-2.9.8.jar:2.9.8]
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:124) [classes/:na]
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:144) [classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.DBTaskResponseProcessor.process(DBTaskResponseProcessor.java:45) [classes/:na]
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128) [classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

**Comment by xingchun-chen** [comment]
Can you describe how this problem occurred

**Comment by chengpeng2015** [comment]
runing task!

You can try this line of code：JSONUtils.parseObject("{\"taskInstanceId\":6,\"status\":7}", DBTaskAckCommand.class)

This line of code appears：DBTaskResponseProcessor.process JSONUtils.parseObject(command.getBody(),DBTaskResponseCommand.class);

**Comment by chengpeng2015** [comment]
【DBTaskAckCommand DBTaskResponseCommand】  These two classes have no constructor, which causes JSON parsing to fail

**Comment by chengpeng2015** [comment]
![Uploading 1606728250(1).jpg…]()
