### ISSUE TITLE
[Bug][common] get system group information error

### ISSUE THREAD

**Issue by chengpeng2015** [apache/incubator-dolphinscheduler#4126]
class: OSUtils
method: getGroup
line: String result = exeCmd(String.format("net user \"%s\"", currentProcUserName));

runing result: ȫ�����Ա             *None                 
����ɹ���ɡ�

Cause array out of bounds！！！ 

error info:
java.lang.ArrayIndexOutOfBoundsException: 22
	at org.apache.dolphinscheduler.common.utils.OSUtils.getGroup(OSUtils.java:367) ~[classes/:na]
	at org.apache.dolphinscheduler.common.utils.OSUtils.createUser(OSUtils.java:261) ~[classes/:na]
	at org.apache.dolphinscheduler.common.utils.FileUtils.createWorkDirAndUserIfAbsent(FileUtils.java:185) ~[classes/:na]
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:120) ~[classes/:na]
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128) ~[classes/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

**PS: My computer is Chinese ，Does the result need to be encoded?**

**Comment by xingchun-chen** [comment]
Can you describe how this problem occurred

**Comment by chengpeng2015** [comment]
runing task!   There is no special operation

**Comment by zhuangchong** [comment]
From the error message, the task is running on a Windows machine, the tenant does not exist, and a new tenant needs to be created.
1. Dolphin currently does not support Windows
2. Workers will not be allowed to create new tenants later   #4069

---
从错误信息上看，是在windows机器上跑任务，租户不存在，需要创建新的租户。
1.dolphin目前不支持windows
2.后期将不允许worker创建新的租户

**Comment by CalvinKirs** [comment]
Worker server cannot be deployed on windows
