### ISSUE TITLE
[Bug][SQL] SQL query mode exception : Failed to obtain JDBC Connection ...

### ISSUE THREAD

**Issue by BoYiZhang** [apache/incubator-dolphinscheduler#4161]
version : 1.3.2

SQL query mode exception : Failed to obtain JDBC Connection ...

The Worker service connects to the database normally, the shell node can query the database normally, and the SQL component "non-query mode" is used normally.
But using "query mode" reports an error.
The exception information is as follows:

![image](https://user-images.githubusercontent.com/39816903/101117241-89e15a00-3621-11eb-8769-cc3fa5ee56d4.png)

This exception also exists in the official druid, and the related issues are as follows:

https://github.com/alibaba/druid/issues/2130

User feedback screenshot:

![image](https://user-images.githubusercontent.com/39816903/101117477-ffe5c100-3621-11eb-8890-bd26ad980233.png)
![image](https://user-images.githubusercontent.com/39816903/101117500-0c6a1980-3622-11eb-94d3-34bf31c92f48.png)
![image](https://user-images.githubusercontent.com/39816903/101117509-11c76400-3622-11eb-9e78-c9d15d05b082.png)
![image](https://user-images.githubusercontent.com/39816903/101117525-1b50cc00-3622-11eb-9483-c40a451298d9.png)

```
[INFO] 2020-12-03 23:23:48.224  - [taskAppId=TASK-360-52586-96421]:[121] - create dir success /tmp/dolphinscheduler/exec/process/4/360/52586/96421
[INFO] 2020-12-03 23:23:48.340  - [taskAppId=TASK-360-52586-96421]:[87] - sql task params {"type":"MYSQL","datasource":6,"sql":"select * from test1","udfs":"","sqlType":"0","title":"awhtest-邮件发送","receivers":"xxxx@qq.com","receiversCc":"","showType":"TABLE","localParams":[],"connParams":"","preStatements":[],"postStatements":[]}
[INFO] 2020-12-03 23:25:27.338  - [taskAppId=TASK-360-52586-96421]:[103] - Full sql parameters: SqlParameters{type='MYSQL', datasource=6, sql='select * from test1', sqlType=0, udfs='', showType='TABLE', connParams='', title='awhtest-邮件发送', receivers='xxxx@qq.com', receiversCc='', preStatements=[], postStatements=[]}
[INFO] 2020-12-03 23:25:27.339  - [taskAppId=TASK-360-52586-96421]:[104] - sql type : MYSQL, datasource : 6, sql : select * from test1 , localParams : [],udfs : ,showType : TABLE,connParams : 
[INFO] 2020-12-03 23:25:27.359  - [taskAppId=TASK-360-52586-96421]:[175] - SQL title : awhtest-邮件发送
[INFO] 2020-12-03 23:25:27.365  - [taskAppId=TASK-360-52586-96421]:[494] - after replace sql , preparing : select * from test1
[INFO] 2020-12-03 23:25:27.366  - [taskAppId=TASK-360-52586-96421]:[499] - Sql Params are replaced sql , parameters:
[INFO] 2020-12-03 23:25:27.368  - [taskAppId=TASK-360-52586-96421]:[52] - can't find udf function resource
[INFO] 2020-12-03 23:25:27.639  - [taskAppId=TASK-360-52586-96421]:[413] - prepare statement replace sql : com.mysql.jdbc.JDBC42PreparedStatement@3ad2f168: select * from test1 
[ERROR] 2020-12-03 23:27:27.696  - [taskAppId=TASK-360-52586-96421]:[242] - execute sql error
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
### The error may exist in file [/opt/ds-1.3.2-agent/conf/org/apache/dolphinscheduler/dao/mapper/UserAlertGroupMapper.xml]
### The error may involve org.apache.dolphinscheduler.dao.mapper.UserAlertGroupMapper.listUserByAlertgroupId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:78)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy91.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:223)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.executeForMany(MybatisMapperMethod.java:158)
	at com.baomidou.mybatisplus.core.override.MybatisMapperMethod.execute(MybatisMapperMethod.java:76)
	at com.baomidou.mybatisplus.core.override.MybatisMapperProxy.invoke(MybatisMapperProxy.java:61)
	at com.sun.proxy.$Proxy94.listUserByAlertgroupId(Unknown Source)
	at org.apache.dolphinscheduler.dao.AlertDao.queryUserByAlertGroupId(AlertDao.java:97)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.sendAttachment(SqlTask.java:424)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.resultProcess(SqlTask.java:273)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:232)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:138)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
### The error may exist in file [/opt/ds-1.3.2-agent/conf/org/apache/dolphinscheduler/dao/mapper/UserAlertGroupMapper.xml]
### The error may involve org.apache.dolphinscheduler.dao.mapper.UserAlertGroupMapper.listUserByAlertgroupId
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 17 common frames omitted
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:80)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:67)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.prepareStatement(MybatisSimpleExecutor.java:93)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQuery(MybatisSimpleExecutor.java:66)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 23 common frames omitted
Caused by: com.alibaba.druid.pool.GetConnectionTimeoutException: wait millis 60000, active 0, maxActive 50, creating 1, createElapseMillis 121719, createErrorCount 1
	at com.alibaba.druid.pool.DruidDataSource.getConnectionInternal(DruidDataSource.java:1737)
	at com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1409)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1389)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1379)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:157)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	... 32 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1644)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1710)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:923)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1383)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1379)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:109)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseProductName(VendorDatabaseIdProvider.java:79)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseName(VendorDatabaseIdProvider.java:63)
	at org.apache.ibatis.mapping.VendorDatabaseIdProvider.getDatabaseId(VendorDatabaseIdProvider.java:50)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.buildSqlSessionFactory(MybatisSqlSessionFactoryBean.java:555)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.afterPropertiesSet(MybatisSqlSessionFactoryBean.java:426)
	at com.baomidou.mybatisplus.extension.spring.MybatisSqlSessionFactoryBean.getObject(MybatisSqlSessionFactoryBean.java:624)
	at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory.sqlSessionFactory(SpringConnectionFactory.java:137)
	at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8023f944.CGLIB$sqlSessionFactory$3(<generated>)
	at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8023f944$$FastClassBySpringCGLIB$$c745e5f8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.apache.dolphinscheduler.dao.datasource.SpringConnectionFactory$$EnhancerBySpringCGLIB$$8023f944.sqlSessionFactory(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1484)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1379)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1247)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1167)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1395)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
	at org.apache.dolphinscheduler.server.worker.WorkerServer.main(WorkerServer.java:81)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
	... 103 common frames omitted
[ERROR] 2020-12-03 23:27:27.702  - [taskAppId=TASK-360-52586-96421]:[144] - sql task error
java.lang.RuntimeException: execute sql error
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:243)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:138)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:149)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

-------------------------------------------------------------

Worker服务正常连接数据库, shell节点可以正常查询数据库, SQL组件 "非查询模式"正常使用.
但是使用"查询模式"报错.
异常信息如下:

![image](https://user-images.githubusercontent.com/39816903/101117241-89e15a00-3621-11eb-8769-cc3fa5ee56d4.png)

druid 官方也存在这个异常,相关issue如下:

https://github.com/alibaba/druid/issues/2130

---------------------------------------------
用户反馈截图:

![image](https://user-images.githubusercontent.com/39816903/101117477-ffe5c100-3621-11eb-8890-bd26ad980233.png)
![image](https://user-images.githubusercontent.com/39816903/101117500-0c6a1980-3622-11eb-94d3-34bf31c92f48.png)
![image](https://user-images.githubusercontent.com/39816903/101117509-11c76400-3622-11eb-9e78-c9d15d05b082.png)
![image](https://user-images.githubusercontent.com/39816903/101117525-1b50cc00-3622-11eb-9483-c40a451298d9.png)

**Comment by CalvinKirs** [comment]
Does the thread of the database itself reach the limit of max conn?

**Comment by CalvinKirs** [comment]
If the direct connection is possible, but the drive connection is not good, then there may be a drive problem. It is recommended to replace the drive.

**Comment by anan0120** [comment]
I have been tossing about the problem for a few days, and I have not been able to locate the specific cause. The driver has also been changed to 5.1.48, the server restarted and other methods have been tried without solution.

It's hard to understand: other operations don't even have any problems with data. Only this sql component sql type is query, and the problem of druid timeout has been reported. I have been thinking about the details of eating, walking, and sleeping that I have overlooked. . . I finally decided on the machine room migration, and then took a look at the configuration file. The effort paid off. I really located the reason.

Looking at the scheduling configuration file, it turns out that the master's database configuration is modified normally (so the main functions are not affected), and the metadata configuration on the worker has not been completely modified

In the process of locating this problem, several big guys on the official website have been bothered by me. Thank you again for your patient guidance! !

**Comment by CalvinKirs** [comment]
> I have been tossing about the problem for a few days, and I have not been able to locate the specific cause. The driver has also been changed to 5.1.48, the server restarted and other methods have been tried without solution.
> 
> It's hard to understand: other operations don't even have any problems with data. Only this sql component sql type is query, and the problem of druid timeout has been reported. I have been thinking about the details of eating, walking, and sleeping that I have overlooked. . . I finally decided on the machine room migration, and then took a look at the configuration file. The effort paid off. I really located the reason.
> 
> Looking at the scheduling configuration file, it turns out that the master's database configuration is modified normally (so the main functions are not affected), and the metadata configuration on the worker has not been completely modified
> 
> In the process of locating this problem, several big guys on the official website have been bothered by me. Thank you again for your patient guidance! !

Thx，I will close it.

**Comment by arvindparaliya** [comment]
Hi, I need some help with a MySQL JDBC connection issue that I've been struggling with for the past 3 months. I’ve tried almost everything.

**org.springframework.jdbc.cannotgetjdbcconnectionexception: failed to obtain jdbc connection after some time**

MySQL version: 8.0.42
Driver: I tried both mysql-connector-java-8.4.0 and 5.1.48
Java: Using Corretto 21
OS: Windows 11
IDE: IntelliJ and Eclipse (same issue)
MySQL service is running
Credentials are correct (I can log in with the same root user and password using MySQL CLI and Workbench)

Still, in Java, it throws:
org.springframework.jdbc.cannotgetjdbcconnectionexception: failed to obtain jdbc connection after some time.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
Things I’ve tried:
✔ Verified user privileges
✔ Reinstalled MySQL multiple times
✔ Tried different drivers
✔ Disabled sleep/hibernate
✔ Rechecked JDBC URL with useSSL=false&allowPublicKeyRetrieval=true
✔ Even tested with plain JDBC code — same result
✔ Restarted laptop and MySQL many times

I’m really stuck and losing a lot of time due to this. If you’ve experienced this or can guide me, it would mean a lot 🙏
