### ISSUE TITLE
[Bug][Master] After clicking execute workflow, the Master node reported an error

### ISSUE THREAD

**Issue by imyoubo** [apache/incubator-dolphinscheduler#4185]
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
When I click to run a workflow, I find that the Master node is reporting an error

**Screenshots**
![image](https://user-images.githubusercontent.com/41062250/101578370-ca234c80-3a14-11eb-8bb4-54cdfd0fdea9.png)

**Which version of Dolphin Scheduler:**
 -[1.3.3]

**Additional context**
[INFO] 2020-12-09 10:55:20.965 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[132] - find one command: id: 30001, type: START_PROCESS
[ERROR] 2020-12-09 10:55:20.966 org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService:[144] - scan command error
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager' defined in class path resource [org/apache/dolphinscheduler/dao/datasource/SpringConnectionFactory.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1115)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:394)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:284)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at org.apache.dolphinscheduler.service.process.ProcessService$$EnhancerBySpringCGLIB$$a78f4bf1.handleCommand(<generated>)
        at org.apache.dolphinscheduler.server.master.runner.MasterSchedulerService.run(MasterSchedulerService.java:136)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:392)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1305)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1144)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by imyoubo** [comment]
I based on the 1.3.3 version of the source code after the recompilation of this problem

**Comment by CalvinKirs** [comment]
Can you provide a complete log, preferably not using pictures

**Comment by imyoubo** [comment]
I have solved the problem, but I find it very strange

> Can you provide a complete log, preferably not using pictures

Oh, I've solved this problem, but I find it puzzling, and it goes like this:

Based on the stable version 1.3.3, I added LDAP authentication.In the "org.apache.dolphinscheduler.api.security.SecurityConfig" this class, I've added a configuration item (by `@ Value (" ${ldap. Url} ")` way to read the "application-api.properties" in the configuration file is the Value), as shown in the figure below

![image](https://user-images.githubusercontent.com/41062250/101754153-611fff80-3b0e-11eb-9c47-90e222b98791.png)
![image](https://user-images.githubusercontent.com/41062250/101754241-7ac14700-3b0e-11eb-8b39-212a7964e51e.png)
![image](https://user-images.githubusercontent.com/41062250/101754475-be1bb580-3b0e-11eb-8cd2-eda3d1937081.png)

The problem was with this configuration, when I changed the name of the configuration to `ldap.addr`, the problem was solved.😂😂😂
![image](https://user-images.githubusercontent.com/41062250/101754523-cb38a480-3b0e-11eb-9553-24aa7797c58b.png)

I am very surprised what is the relationship between the configuration of `ldap.url` and the Master node, why this configuration causes the Master node to report an error, and this problem does not appear when I do not click to execute the task, the user can log in through LDAP normally Authentication, only when I click on an online task and run it, the Master node will report an error frantically and log, which makes it difficult for me to understand.

I guess the program treats this configuration as a database connection string?

---
这个问题我已经解决了，但是对这个问题我很费解，它是这样的
基于1.3.3稳定版本，我增加了基于LDAP认证的功能。在"org.apache.dolphinscheduler.api.security.SecurityConfig"这个类中，我增加了一个配置项(通过`@ Value (" ${ldap. Url} ")`的方式读取"application-api.properties"这个配置文件中的值)，如下图所示。
问题就出在这个配置上，当我把这个配置的名称改为`ldap.addr`，问题就解决了。😂😂😂

我很好奇这个配置和Master节点有什么关系，为什么这个配置会导致Master节点报错，而且，这个问题在我不点击执行任务的时候是没有问题的，用户可以正常登陆通过LDAP身份认证，只有当我点击某个在线的任务并运行它，Master节点就会疯狂的报错，输入日志，这让我很费解。。。

我猜想是程序把这个配置当成了一个数据库连接串吗？
