### ISSUE TITLE
[Bug][common]  Cannot construct instance... (no Creators, like default construct, exist)

### ISSUE THREAD

**Issue by dailidong** [apache/incubator-dolphinscheduler#4191]
**Describe the bug**
when run a Process Definition， An exception throws in worker server runtime log, as follow:

[ERROR] 2020-12-09 17:38:14.996 org.apache.dolphinscheduler.common.utils.JSONUtils:[126] - parse object exception!
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.apache.dolphinscheduler.remote.command.DBTaskResponseCommand` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"taskInstanceId":15,"status":7}"; line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:124)
	at org.apache.dolphinscheduler.common.utils.JSONUtils.parseObject(JSONUtils.java:144)
	at org.apache.dolphinscheduler.server.worker.processor.DBTaskResponseProcessor.process(DBTaskResponseProcessor.java:45)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 

**Which version of Dolphin Scheduler:**
 -[dev]

**Comment by dailidong** [comment]
the same issue with #4125 , I will close this issue
