### ISSUE TITLE
[question] create tenant failure

### ISSUE THREAD

**Issue by zongqiren** [apache/incubator-dolphinscheduler#4193]
我们使用的是开启了keberos的集群，在dolphinscheduler 的conf目录下的common.properties 配置了kerberos相关的参数，但是在ds界面上用创建租户失败，配置文件截图
![common](https://user-images.githubusercontent.com/43920272/101644985-d0471680-3a70-11eb-9ccb-2265d5e36202.png)

报错截图为：
![error](https://user-images.githubusercontent.com/43920272/101647071-477daa00-3a73-11eb-8162-66a80b1ee22b.png)
求助各位大佬

**Comment by zongqiren** [comment]
# whether kerberos starts
hadoop.security.authentication.startup.state=false
common配置
# java.security.krb5.conf.path=/opt/apps/dolphinscheduler/conf/krb5.conf
java.security.krb5.conf.path=/opt/apps/dolphinscheduler/conf/krb5.conf

# login user from keytab username
login.user.keytab.username=hdfs

# loginUserFromKeytab path
login.user.keytab.path=/opt/apps/dolphinscheduler/conf/hdfs.keytab

#resource.view.suffixs
#resource.view.suffixs=txt,log,sh,conf,cfg,py,java,sql,hql,xml,properties

# if resource.storage.type=HDFS
hdfs.root.user=hdfs

**Comment by zongqiren** [comment]
error信息：
[ERROR] 2020-12-09 23:04:48.227 org.apache.dolphinscheduler.common.utils.HadoopUtils:[102] - org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
org.apache.hadoop.security.AccessControlException: org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
