### ISSUE TITLE
start api-server error (启动api-server报错)

### ISSUE THREAD

**Issue by CrazyBeeline** [apache/incubator-dolphinscheduler#4194]
版本:1.3.3
os:centos7.6
java:1.8.0_181

![image](https://user-images.githubusercontent.com/25030234/101710626-d539b380-3acc-11eb-9fbf-6c19f40dbf89.png)

**Comment by CalvinKirs** [comment]
Did you build it yourself or use the official release package?

**Comment by CrazyBeeline** [comment]
是的我自己编译的cdh6.3.2版
yes I compile it with CDH6.3.2

**Comment by CalvinKirs** [comment]
> 是的我自己编译的cdh6.3.2版
> yes I compile it with CDH6.3.2

Do you have another Jetty binaries on the classpath?

**Comment by CrazyBeeline** [comment]
![Uploading image.png…]()

**Comment by CrazyBeeline** [comment]
![image](https://user-images.githubusercontent.com/25030234/101749356-9b869e00-3b08-11eb-9f72-398c0dce58bc.png)
if I have another Jetty binaries

**Comment by CalvinKirs** [comment]
You should exclude Jetty dependency

**Comment by CrazyBeeline** [comment]
ok ths

**Comment by CrazyBeeline** [comment]
我用了官方提供的lib，替换了hadoop和hive的jar包 问题解决了  ths

**Comment by PotatoDream** [comment]
请问使用编译命令：mvn -U clean package -Prelease -Dmaven.test.skip=true -Dmaven.javadoc.skip=true编译dolphinscheduler-1.3.4-cdh6.3.2成功后，启动后api-server日志中报错：
Caused by: java.lang.ClassNotFoundException: org.mortbay.log.Log
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at com.sun.org.apache.commons.logging.JettyLog.<init>(JettyLog.java:36) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at com.sun.org.apache.commons.logging.LogFactory.getLog(LogFactory.java:35) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at org.apache.jasper.runtime.JspFactoryImpl.<clinit>(JspFactoryImpl.java:84) ~[jsp-2.1-6.1.14.jar:6.1.14]
        at org.apache.jasper.servlet.JasperInitializer.<clinit>(JasperInitializer.java:51) ~[jetty-runner-9.3.25.v20180904.jar:6.1.14]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_181]
