### ISSUE TITLE
no netty_transport_native_epoll_x86_64 in java.library.path

### ISSUE THREAD

**Issue by fanghj** [apache/incubator-dolphinscheduler#4205]
DS : 13.3

when I start log-server get logs such as :+1: 

10:35:33.963 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
10:35:33.973 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
10:35:33.974 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
10:35:34.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
10:35:34.010 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
10:35:34.012 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
10:35:34.012 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
10:35:34.013 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
10:35:34.013 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
10:35:34.014 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
10:35:34.014 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
10:35:34.014 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
10:35:34.014 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
10:35:34.015 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
10:35:34.015 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
10:35:34.016 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
10:35:34.016 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1021313024 bytes
10:35:34.016 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
10:35:34.017 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
10:35:34.018 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
10:35:34.021 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:229)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:221)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:207)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at org.apache.dolphinscheduler.remote.utils.NettyUtils.useEpoll(NettyUtils.java:41)
	at org.apache.dolphinscheduler.remote.NettyRemotingServer.<init>(NettyRemotingServer.java:102)
	at org.apache.dolphinscheduler.server.log.LoggerServer.<init>(LoggerServer.java:53)
	at org.apache.dolphinscheduler.server.log.LoggerServer.main(LoggerServer.java:66)
10:35:34.022 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:215)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at org.apache.dolphinscheduler.remote.utils.NettyUtils.useEpoll(NettyUtils.java:41)
	at org.apache.dolphinscheduler.remote.NettyRemotingServer.<init>(NettyRemotingServer.java:102)
	at org.apache.dolphinscheduler.server.log.LoggerServer.<init>(LoggerServer.java:53)
	at org.apache.dolphinscheduler.server.log.LoggerServer.main(LoggerServer.java:66)
10:35:34.033 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library '/tmp/libnetty_transport_native_epoll_x86_641877825885176952225.so', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: Method io.netty.channel.epoll.Native.sendmmsg0(I[Lio/netty/channel/epoll/NativeDatagramPacketArray$NativeDatagramPacket;II)I name or signature does not match
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:242)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:207)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:167)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at org.apache.dolphinscheduler.remote.utils.NettyUtils.useEpoll(NettyUtils.java:41)
	at org.apache.dolphinscheduler.remote.NettyRemotingServer.<init>(NettyRemotingServer.java:102)
	at org.apache.dolphinscheduler.server.log.LoggerServer.<init>(LoggerServer.java:53)
	at org.apache.dolphinscheduler.server.log.LoggerServer.main(LoggerServer.java:66)
10:35:34.040 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 48
10:35:34.067 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
10:35:34.067 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
10:35:34.078 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
10:35:34.107 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 4561 (auto-detected)
10:35:34.109 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
10:35:34.109 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
10:35:34.111 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 127.0.0.1)
10:35:34.111 [main] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
10:35:34.114 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 52:54:00:ff:fe:2b:83:69 (auto-detected)
10:35:34.128 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
10:35:34.128 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
10:35:34.128 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxSampledRecords: 40
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 10
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 10
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
10:35:34.155 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
10:35:34.164 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
10:35:34.164 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
10:35:34.165 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
10:35:34.181 [main] INFO org.apache.dolphinscheduler.remote.NettyRemotingServer - NettyRemotingServer bind success at port : 50051
10:35:34.181 [main] INFO org.apache.dolphinscheduler.server.log.LoggerServer - logger server started, listening on port : 50051

**Comment by CalvinKirs** [comment]
1: Can the service be started normally?
2: Is there the following log: io.netty.util.internal.NativeLibraryLoader-Successfully loaded the library

**Comment by fanghj** [comment]
> 1: Can the service be started normally?
> 2: Is there the following log: io.netty.util.internal.NativeLibraryLoader-Successfully loaded the library

yes, the log-server running is ok . error just when I start log-server

**Comment by CalvinKirs** [comment]
Is there the following log: io.netty.util.internal.NativeLibraryLoader-Successfully loaded the library ?

**Comment by fanghj** [comment]
> Is there the following log: io.netty.util.internal.NativeLibraryLoader-Successfully loaded the library ?

NO, 
10:35:34.021 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.

**Comment by CalvinKirs** [comment]
This is the debug log. It is just for debugging convenience. According to past experience, it often goes to other paths to find epoll related files.
