### ISSUE TITLE
界面查看任务日志加载不出来

### ISSUE THREAD

**Issue by fanghj** [apache/incubator-dolphinscheduler#4209]
任务日志在服务器上存在。界面点击下载到本地可查看，但是界面加载查看加载不出来。
DS版本:1.3.3
application-api.properties  中 server.servlet.session.timeout=60000 值设置大些无效

![image](https://user-images.githubusercontent.com/21124391/101872050-95072d80-3bbf-11eb-937d-186dec62176b.png)

api-server.log 报错连接超时

[ERROR] 2020-12-11 14:34:44.353 org.apache.dolphinscheduler.service.log.LogClientService:[85] - roll view log error
org.apache.dolphinscheduler.remote.exceptions.RemotingTimeoutException: wait response on the channel Host{address='10.135.142.234:50051'} timeout 10000
	at org.apache.dolphinscheduler.remote.NettyRemotingClient.sendSync(NettyRemotingClient.java:287)
	at org.apache.dolphinscheduler.service.log.LogClientService.rollViewLog(LogClientService.java:78)
	at org.apache.dolphinscheduler.api.service.LoggerService.queryLog(LoggerService.java:78)
	at org.apache.dolphinscheduler.api.controller.LoggerController.queryLog(LoggerController.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:84)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
[WARN] 2020-12-11 14:34:46.099 org.apache.dolphinscheduler.remote.future.ResponseFuture:[185] - remove timeout request : ResponseFuture{opaque=8, timeoutMillis=10000, invokeCallback=null, releaseSemaphore=null, latch=java.util.concurrent.CountDownLatch@6512787c[Count = 1], beginTimestamp=1607668474352, responseCommand=null, sendOk=true, cause=null}

**Comment by CalvinKirs** [comment]
Please confirm whether the network is normal. I observed that after netty sent the message, the sending result was not received within the set timeout period.

**Comment by fanghj** [comment]
> Please confirm whether the network is normal. I observed that after netty sent the message, the sending result was not received within the set timeout period.

the network is ok 
![image](https://user-images.githubusercontent.com/21124391/101882097-57f76700-3bd0-11eb-97f3-6381034b5d09.png)

**Comment by CalvinKirs** [comment]
Does this problem often occur? Have you tried smaller data?

**Comment by fanghj** [comment]
yes,the problem is always there. and the date is not big







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-dolphinscheduler"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 晚上6:33
收件人:&nbsp;"apache/incubator-dolphinscheduler"<incubator-dolphinscheduler@noreply.github.com&gt;;
抄送:&nbsp;"272522209"<272522209@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-dolphinscheduler] 界面查看任务日志加载不出来 (#4209)





 
Does this problem often occur? Have you tried smaller data?

**Comment by fanghj** [comment]
> Does this problem often occur? Have you tried smaller data?

[INFO] 2020-12-14 11:22:02.903 org.apache.dolphinscheduler.api.service.LoggerService:[76] - log host : 10.135.142.234 , logPath : /mydata/dolphinscheduler/logs/2/1358/3672.log , logServer port : 50051
[INFO] 2020-12-14 11:22:02.904 org.apache.dolphinscheduler.service.log.LogClientService:[72] - roll view log, host : 10.135.142.234, port : 50051, path /mydata/dolphinscheduler/logs/2/1358/3672.log, skipLineNum 0 ,limit 1000
[ERROR] 2020-12-14 11:22:13.013 org.apache.dolphinscheduler.service.log.LogClientService:[85] - roll view log error
org.apache.dolphinscheduler.remote.exceptions.RemotingTimeoutException: wait response on the channel Host{address='10.135.142.234:50051'} timeout 10000
	at org.apache.dolphinscheduler.remote.NettyRemotingClient.sendSync(NettyRemotingClient.java:287)
	at org.apache.dolphinscheduler.service.log.LogClientService.rollViewLog(LogClientService.java:78)
	at org.apache.dolphinscheduler.api.service.LoggerService.queryLog(LoggerService.java:78)
	at org.apache.dolphinscheduler.api.controller.LoggerController.queryLog(LoggerController.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

hi,about this error. I see the load log timeout failed.Where can I set or adjust the load time

**Comment by CalvinKirs** [comment]
> > Does this problem often occur? Have you tried smaller data?
> 
> [INFO] 2020-12-14 11:22:02.903 org.apache.dolphinscheduler.api.service.LoggerService:[76] - log host : 10.135.142.234 , logPath : /mydata/dolphinscheduler/logs/2/1358/3672.log , logServer port : 50051
> [INFO] 2020-12-14 11:22:02.904 org.apache.dolphinscheduler.service.log.LogClientService:[72] - roll view log, host : 10.135.142.234, port : 50051, path /mydata/dolphinscheduler/logs/2/1358/3672.log, skipLineNum 0 ,limit 1000
> [ERROR] 2020-12-14 11:22:13.013 org.apache.dolphinscheduler.service.log.LogClientService:[85] - roll view log error
> org.apache.dolphinscheduler.remote.exceptions.RemotingTimeoutException: wait response on the channel Host{address='10.135.142.234:50051'} timeout 10000
> at org.apache.dolphinscheduler.remote.NettyRemotingClient.sendSync(NettyRemotingClient.java:287)
> at org.apache.dolphinscheduler.service.log.LogClientService.rollViewLog(LogClientService.java:78)
> at org.apache.dolphinscheduler.api.service.LoggerService.queryLog(LoggerService.java:78)
> at org.apache.dolphinscheduler.api.controller.LoggerController.queryLog(LoggerController.java:79)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> hi,about this error. I see the load log timeout failed.Where can I set or adjust the load time

This parameter has not been exposed. The default parameters are sufficient under normal circumstances.

**Comment by fanghj** [comment]
hi guys.I have found the cause of the problem.
When I started a service with a command: sh start-all.sh, some services started twice.
So,when I kill some services about twice ,the logs will be read in the page.
Thank you for your help.


![image](https://user-images.githubusercontent.com/21124391/102158764-20810700-3ebd-11eb-8ca9-c6921e9dfd36.png)
