### ISSUE TITLE
[Bug][common] MacOS run shell script faild

### ISSUE THREAD

**Issue by zzq1314zll** [apache/incubator-dolphinscheduler#4315]
```java
[INFO] 2020-12-26 16:30:52.302  - [taskAppId=TASK-1-3-15]:[115] - create dir success /tmp/dolphinscheduler/exec/process/1/1/3/15
[INFO] 2020-12-26 16:30:55.512  - [taskAppId=TASK-1-3-15]:[115] - create mac os user : 000000000001
[INFO] 2020-12-26 16:30:55.512  - [taskAppId=TASK-1-3-15]:[115] - create user command : sudo sysadminctl -addUser 000000000001 -password 000000000001
[ERROR] 2020-12-26 16:30:55.734  - [taskAppId=TASK-1-3-15]:[105] - sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

org.apache.dolphinscheduler.common.shell.AbstractShell$ExitCodeException: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

	at org.apache.dolphinscheduler.common.shell.AbstractShell.runCommand(AbstractShell.java:209)
	at org.apache.dolphinscheduler.common.shell.AbstractShell.run(AbstractShell.java:124)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execute(ShellExecutor.java:127)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:104)
	at org.apache.dolphinscheduler.common.shell.ShellExecutor.execCommand(ShellExecutor.java:87)
	at org.apache.dolphinscheduler.common.utils.OSUtils.exeShell(OSUtils.java:379)
	at org.apache.dolphinscheduler.common.utils.OSUtils.exeCmd(OSUtils.java:369)
	at org.apache.dolphinscheduler.common.utils.OSUtils.createMacUser(OSUtils.java:296)
	at org.apache.dolphinscheduler.common.utils.OSUtils.createUser(OSUtils.java:244)
	at org.apache.dolphinscheduler.common.utils.FileUtils.createWorkDirAndUserIfAbsent(FileUtils.java:175)
	at org.apache.dolphinscheduler.server.worker.processor.TaskExecuteProcessor.process(TaskExecuteProcessor.java:139)
	at org.apache.dolphinscheduler.remote.handler.NettyServerHandler$1.run(NettyServerHandler.java:128)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-12-26 16:30:55.735  - [taskAppId=TASK-1-3-15]:[115] - create user name fail 000000000001
[INFO] 2020-12-26 16:30:56.923  - [taskAppId=TASK-1-3-15]:[85] - shell task params {"rawScript":"echo 'hello1'","localParams":[],"resourceList":[]}
[INFO] 2020-12-26 16:30:56.958  - [taskAppId=TASK-1-3-15]:[160] - raw script : echo 'hello1'
[INFO] 2020-12-26 16:30:56.958  - [taskAppId=TASK-1-3-15]:[161] - task execute path : /tmp/dolphinscheduler/exec/process/1/1/3/15
[INFO] 2020-12-26 16:30:56.963  - [taskAppId=TASK-1-3-15]:[87] - tenantCode user:000000000001, task dir:1_3_15
[INFO] 2020-12-26 16:30:56.964  - [taskAppId=TASK-1-3-15]:[92] - create command file:/tmp/dolphinscheduler/exec/process/1/1/3/15/1_3_15.command
[INFO] 2020-12-26 16:30:56.965  - [taskAppId=TASK-1-3-15]:[111] - command : #!/bin/sh
BASEDIR=$(cd `dirname $0`; pwd)
cd $BASEDIR
source /etc/profile
/tmp/dolphinscheduler/exec/process/1/1/3/15/1_3_15_node.sh
[INFO] 2020-12-26 16:30:56.977  - [taskAppId=TASK-1-3-15]:[324] - task run command:
sudo -u 000000000001 sh /tmp/dolphinscheduler/exec/process/1/1/3/15/1_3_15.command
[INFO] 2020-12-26 16:30:56.984  - [taskAppId=TASK-1-3-15]:[205] - process start, process id is: 41046
[INFO] 2020-12-26 16:30:57.075  - [taskAppId=TASK-1-3-15]:[214] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/1/1/3/15, processId:41046 ,exitStatusCode:0
[INFO] 2020-12-26 16:30:57.080  - [taskAppId=TASK-1-3-15]:[127] -  -> sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

```

**Comment by zzq1314zll** [comment]
I append the parameters '-S'，There is no change in the task status

**Comment by CalvinKirs** [comment]
Need to set up password-free login

**Comment by zzq1314zll** [comment]
@CalvinKirs  程序先查看执行这个任务的用户存不存在，如果不存在创建用户，创建目录，执行任务，但是现在程序根据都找不到执行任务的这个用户，但是实际情况是用户已经存在了（我通过手动在命令行执行命令）

**Comment by CalvinKirs** [comment]
> @CalvinKirs 程序先查看执行这个任务的用户存不存在，如果不存在创建用户，创建目录，执行任务，但是现在程序根据都找不到执行任务的这个用户，但是实际情况是用户已经存在了（我通过手动在命令行执行命令）

sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper

**Comment by chengshiwen** [comment]
Close this question since no updates for long time

**Comment by Atom-me** [comment]
@zzq1314zll @CalvinKirs Did you resolve this problem?

**Comment by jim-parsons** [comment]
> [solution](https://apple.stackexchange.com/questions/257813/enable-sudo-without-a-password-on-macos)

![image](https://user-images.githubusercontent.com/20239172/148038452-a61b321c-0b72-4076-9a6d-9a37dfbd3a48.png)

**Comment by klboke** [comment]
https://github.com/apache/dolphinscheduler/issues/8295#issuecomment-1362464088
