### ISSUE TITLE
[Question] Debugging dataX under windows and calling CMD command to report an error ，Win32Exception: 句柄无效。

### ISSUE THREAD

**Issue by baiyibo** [apache/incubator-dolphinscheduler#4317]
Environment: DS 1.3.2-snapshot, JDK 1.8, Python 2.7.18

When debugging dataX in windows, when creating a process to call the bat file of dataX generated by DS, execute the CMD command and report an error. The log is as follows:
(Note: in windows, you can run dataX by double clicking the bat directly without any error)

[INFO] 2020-12-28 09:21:46.714  - [taskAppId=TASK-138-interactive-300]:[316] - task run command:
cmd.exe /c D:\workspace\incubator-dolphinscheduler\exec\interactive\1\138\300\138_interactive_300.bat
[INFO] 2020-12-28 09:21:46.716  - [taskAppId=TASK-138-interactive-300]:[200] - process start, process id is: 0
[ERROR] 2020-12-28 09:21:46.720  - [taskAppId=TASK-138-interactive-300]:[153] - datax task failure
com.sun.jna.platform.win32.Win32Exception: 句柄无效。
	at org.apache.dolphinscheduler.common.utils.process.ProcessImplForWin32.getExitCodeProcess(ProcessImplForWin32.java:760)
	at org.apache.dolphinscheduler.common.utils.process.ProcessImplForWin32.waitFor(ProcessImplForWin32.java:563)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:206)
	at org.apache.dolphinscheduler.server.worker.task.datax.DataxTask.handle(DataxTask.java:146)
	at org.apache.dolphinscheduler.server.worker.runner.BaseTaskExecute.exec(BaseTaskExecute.java:120)
	at org.apache.dolphinscheduler.server.worker.runner.InteractiveTaskExecuteThread.run(InteractiveTaskExecuteThread.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by baiyibo** [comment]
中文再描述一下，就是我在调试dataX的时候，ds生成bat再调用cmd命令执行bat,此时报错 如：
com.sun.jna.platform.win32.Win32Exception: 句柄无效。
	at org.apache.dolphinscheduler.common.utils.process.ProcessImplForWin32.getExitCodeProcess(ProcessImplForWin32.java:760)
	at org.apache.dolphinscheduler.common.utils.process.ProcessImplForWin32.waitFor(ProcessImplForWin32.java:563)
	at org.apache.dolphinscheduler.server.worker.task.AbstractCommandExecutor.run(AbstractCommandExecutor.java:206)
	at org.apache.dolphinscheduler.server.worker.task.datax.DataxTask.handle(DataxTask.java:146)
	at org.apache.dolphinscheduler.server.worker.runner.BaseTaskExecute.exec(BaseTaskExecute.java:120)
	at org.apache.dolphinscheduler.server.worker.runner.InteractiveTaskExecuteThread.run(InteractiveTaskExecuteThread.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

直接在文件夹运行这个生成的bat文件是可以执行的，没有报错，不知道是什么原因

**Comment by CalvinKirs** [comment]
DS does not support bat type. In addition, this code is already in dev

delete

**Comment by dailidong** [comment]
DolphinScheduler not support windows OS yet
