### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by fanghj** [apache/incubator-dolphinscheduler#4323]
hi guys， I have a problem. When I start master server, the log reports an error. I want to know which mastewr node port is occupied

 the log is follow:

[INFO] 2020-12-28 16:21:32.624 org.apache.zookeeper.ClientCnxn:[879] - Socket connection established to masterb/10.104.17.68:2181, initiating session
[INFO] 2020-12-28 16:21:32.629 org.apache.zookeeper.ClientCnxn:[1299] - Session establishment complete on server masterb/10.104.17.68:2181, sessionid = 0x476997176c01946, negotiated timeout = 60000
[INFO] 2020-12-28 16:21:32.630 org.apache.curator.framework.state.ConnectionStateManager:[251] - State change: CONNECTED
[INFO] 2020-12-28 16:21:32.631 org.apache.dolphinscheduler.service.zk.ZookeeperCachedOperator:[55] - add listener to zk path: /dolphinscheduler
[ERROR] 2020-12-28 16:21:32.938 org.apache.dolphinscheduler.remote.NettyRemotingServer:[167] - NettyRemotingServer bind fail bind(..) failed: Address already in use, exit
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
	at io.netty.channel.unix.Socket.bind(Socket.java:287)
	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:684)
	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:258)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2020-12-28 16:21:32.940 org.apache.dolphinscheduler.server.master.processor.queue.TaskResponseService:[121] - TaskResponseWorker stopped

**Comment by CalvinKirs** [comment]
port :12346

**Comment by fanghj** [comment]
通用领域
生物医药
问题已解决，5678端口被cm-agent占用，修改ds的master端口重启ok

The problem has been solved. Port 5678 is occupied by CM agent. Modify the master port of DS and restart OK
