### ISSUE TITLE
java.lang.RuntimeException: execute sql error

### ISSUE THREAD

**Issue by Yanwenjingcn** [apache/incubator-dolphinscheduler#4621]
when i choose the database clickhouse, run a simple statement like "select 1",

it dose not work 

![image](https://user-images.githubusercontent.com/16257260/106230683-03b15080-622b-11eb-8576-233587c39d52.png)

![image](https://user-images.githubusercontent.com/16257260/106230617-dc5a8380-622a-11eb-8631-023316af47b0.png)

[INFO] 2021-01-29 12:05:25.967  - [taskAppId=TASK-4-30-59]:[115] - create dir success /tmp/dolphinscheduler/exec/process/2/4/30/59
[INFO] 2021-01-29 12:05:25.972  - [taskAppId=TASK-4-30-59]:[87] - sql task params {"postStatements":[],"connParams":"","receiversCc":"","udfs":"","type":"CLICKHOUSE","title":"data","sql":"select 1;","preStatements":[],"sqlType":"0","receivers":"yanwenjing@onething.net","datasource":1,"showType":"TABLE,ATTACHMENT","localParams":[]}
[INFO] 2021-01-29 12:05:25.973  - [taskAppId=TASK-4-30-59]:[103] - Full sql parameters: SqlParameters{type='CLICKHOUSE', datasource=1, sql='select 1;', sqlType=0, udfs='', showType='TABLE,ATTACHMENT', connParams='', title='data', receivers='yanwenjing@onething.net', receiversCc='', preStatements=[], postStatements=[]}
[INFO] 2021-01-29 12:05:25.973  - [taskAppId=TASK-4-30-59]:[104] - sql type : CLICKHOUSE, datasource : 1, sql : select 1; , localParams : [],udfs : ,showType : TABLE,ATTACHMENT,connParams : 
[INFO] 2021-01-29 12:05:25.973  - [taskAppId=TASK-4-30-59]:[175] - SQL title : data
[INFO] 2021-01-29 12:05:25.974  - [taskAppId=TASK-4-30-59]:[494] - after replace sql , preparing : select 1;
[INFO] 2021-01-29 12:05:25.974  - [taskAppId=TASK-4-30-59]:[499] - Sql Params are replaced sql , parameters:
[INFO] 2021-01-29 12:05:25.974  - [taskAppId=TASK-4-30-59]:[52] - can't find udf function resource
[INFO] 2021-01-29 12:05:25.988  - [taskAppId=TASK-4-30-59]:[413] - prepare statement replace sql : ru.yandex.clickhouse.ClickHousePreparedStatementImpl@35756922 
[ERROR] 2021-01-29 12:05:26.273  - [taskAppId=TASK-4-30-59]:[242] - execute sql error
java.lang.RuntimeException: send mail failed!
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.sendAttachment(SqlTask.java:456)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.resultProcess(SqlTask.java:273)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:232)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:138)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ERROR] 2021-01-29 12:05:26.274  - [taskAppId=TASK-4-30-59]:[144] - sql task error
java.lang.RuntimeException: execute sql error
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.executeFuncAndSql(SqlTask.java:243)
	at org.apache.dolphinscheduler.server.worker.task.sql.SqlTask.handle(SqlTask.java:138)
	at org.apache.dolphinscheduler.server.worker.runner.TaskExecuteThread.run(TaskExecuteThread.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhuangchong** [comment]
the task failed because send mail failed, it is recommended to check the alert service configuration or run a non-query type SQL statement.

**Comment by chengshiwen** [comment]
@Yanwenjingcn this pr is duplicated with #4710. 1.3.5-release has fixed this issue, and the dev branch I will submit the new pr in the next few days.

**Comment by chengshiwen** [comment]
@chenxingchun So this pr can be closed

**Comment by chengshiwen** [comment]
@CalvinKirs This pr can be closed
