### ISSUE TITLE
[Bug][Docker] Random PSQLException in docker

### ISSUE THREAD

**Issue by chengshiwen** [apache/incubator-dolphinscheduler#4651]
**For better global communication, Please describe it in English. If you feel the description in English is not clear, then you can append description in Chinese(just for Mandarin(CN)), thx! **
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Start DolphinScheduler by `docker-compose`
2. Run `docker logs -f dolphinscheduler-api`, `docker logs -f dolphinscheduler-master` or `docker logs -f dolphinscheduler-worker`
3. Random PSQLException will occur

**Expected behavior**
PSQLException fixed.

**Screenshots**

```
01:31:44.270 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME,CALENDAR_NAME)
01:31:44.274 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP)
01:31:44.278 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE)
01:31:44.283 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE)
01:31:44.290 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE)
01:31:44.298 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME,NEXT_FIRE_TIME)
01:31:44.309 [main] INFO org.apache.dolphinscheduler.common.utils.ScriptRunner - sql: CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME)
01:31:44.347 [main] ERROR org.apache.dolphinscheduler.common.utils.ScriptRunner - SQLException
org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
    at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:145)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:75)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.runInitDDL(UpgradeDao.java:193)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:122)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:104)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:80)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:71)
    at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:38)
01:31:44.347 [main] ERROR org.apache.dolphinscheduler.common.utils.ScriptRunner - Error executing: CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME)
01:31:44.348 [main] ERROR org.apache.dolphinscheduler.dao.upgrade.UpgradeDao - ERROR: relation "qrtz_triggers" does not exist
org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
    at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:145)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:75)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.runInitDDL(UpgradeDao.java:193)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:122)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:104)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:80)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:71)
    at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:38)
01:31:44.352 [main] ERROR org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler - create DolphinScheduler failed
java.lang.RuntimeException: ERROR: relation "qrtz_triggers" does not exist
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.runInitDDL(UpgradeDao.java:202)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:122)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.initSchema(UpgradeDao.java:104)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinSchedulerSchema(DolphinSchedulerManager.java:80)
    at org.apache.dolphinscheduler.dao.upgrade.DolphinSchedulerManager.initDolphinScheduler(DolphinSchedulerManager.java:71)
    at org.apache.dolphinscheduler.dao.upgrade.shell.CreateDolphinScheduler.main(CreateDolphinScheduler.java:38)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "qrtz_triggers" does not exist
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
    at com.alibaba.druid.pool.DruidPooledStatement.execute(DruidPooledStatement.java:633)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:145)
    at org.apache.dolphinscheduler.common.utils.ScriptRunner.runScript(ScriptRunner.java:75)
    at org.apache.dolphinscheduler.dao.upgrade.UpgradeDao.runInitDDL(UpgradeDao.java:193)
    ... 5 common frames omitted
```

**Which version of Dolphin Scheduler:**
 -[1.3.4]
 -[dev]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by chengshiwen** [comment]
@chenxingchun This pr can be closed
