### ISSUE TITLE
Spark task cannot add additional configuration information to other parameters（Spark 任务 无法在 其他参数 中添加其他配置信息）

### ISSUE THREAD

**Issue by wuchunfu** [apache/incubator-dolphinscheduler#564]
When I run the `Spark` task, when I add other parameters (such as: `--conf spark.ui.port=4040`), the program runs incorrectly.

The following is the error message:

```
[INFO] 2019-07-12 12:24:16.260 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_16_28] -> Exception in thread "main" java.lang.IllegalArgumentException: Missing application Resource.
At org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:253)
At org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitArgs(SparkSubmitCommandBuilder.java:161)
At org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitCommand(SparkSubmitCommandBuilder.java:275)
At org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:152)
At org.apache.spark.launcher.Main.main(Main.java:87)
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 8: --conf: command not found
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 9: --conf: command not found
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 10: --conf: command not found
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 11: --conf: command not found
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 12: --conf: command not found
/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 13: --conf: command not found
```

But when I look at the `1_16_28.command` file in the background, it looks normal and it works fine.

current version:

1.0.4 release

Desired result:

I want to be able to add other parameters of `spark` such as: `--jars, --files, --archives, --conf` format type parameters, and can successfully run a full `spark` task.

---
我在运行 `Spark` 任务的时候，当我添加其他参数（如：`--conf spark.ui.port=4040`）的时候程序运行报错，

以下是报错信息：

```
[INFO] 2019-07-12 12:24:16.260 cn.escheduler.server.worker.log.TaskLogger:[178] - [taskAppId=TASK_1_16_28]  -> Exception in thread "main" java.lang.IllegalArgumentException: Missing application resource.
		at org.apache.spark.launcher.CommandBuilderUtils.checkArgument(CommandBuilderUtils.java:253)
		at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitArgs(SparkSubmitCommandBuilder.java:161)
		at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildSparkSubmitCommand(SparkSubmitCommandBuilder.java:275)
		at org.apache.spark.launcher.SparkSubmitCommandBuilder.buildCommand(SparkSubmitCommandBuilder.java:152)
		at org.apache.spark.launcher.Main.main(Main.java:87)
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 8: --conf: command not found
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 9: --conf: command not found
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 10: --conf: command not found
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 11: --conf: command not found
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 12: --conf: command not found
	/tmp/escheduler/exec/process/1/1/16/28/1_16_28.command: line 13: --conf: command not found
```

但是我在后台查看 `1_16_28.command` 文件的时候看起来都是正常的，而且都可以正常运行。

当前版本：

1.0.4 release

期望结果：

我希望能添加 `spark` 的其他参数如： `--jars、--files、--archives、--conf` 格式类型的参数，并能成功运行一个完整的 `spark` 任务。

**Comment by boandai** [comment]
very good,thx!

**Comment by wuchunfu** [comment]
The problem has been solved.
