### ISSUE TITLE
EasyScheduler 后端部署完成后,缺失API-server和Master-Server服务

### ISSUE THREAD

**Issue by lyonggee** [apache/incubator-dolphinscheduler#791]
问题: 没有 MasterServer  服务 和 ApiApplicationServer 服务;
Mvn手动部署

[root@Master logs]# jps |grep Server
15988 AlertServer
15897 WorkerServer
15935 LoggerServer

*************** API-Server 失败日志 *************************

[INFO] 2019-09-15 14:01:30.807 cn.escheduler.api.ApiApplicationServer:[50] - Starting ApiApplicationServer on Master.Hadoop with PID 14321 (/opt/escheduler/lib/eschedu
ler-api-1.1.0-SNAPSHOT.jar started by root in /opt/escheduler)
[INFO] 2019-09-15 14:01:30.814 cn.escheduler.api.ApiApplicationServer:[675] - No active profile set, falling back to default profiles: default
[INFO] 2019-09-15 14:01:36.369 org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker:[330] - Bean 'org.springframework.transac
tion.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringC
GLIB$$dd4d17c9] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[INFO] 2019-09-15 14:01:36.964 org.eclipse.jetty.util.log:[193] - Logging initialized @9077ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2019-09-15 14:01:37.105 org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory:[143] - Server initialized with port: 12345
[INFO] 2019-09-15 14:01:37.108 org.eclipse.jetty.server.Server:[370] - jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc13
6ad9e6; jvm 1.8.0_121-b13
[WARN] 2019-09-15 14:01:37.155 org.eclipse.jetty.webapp.WebAppContext:[554] - Failed startup of context o.s.b.w.e.j.JettyEmbeddedWebAppContext@6963b88c{application,/es
cheduler,[file:///tmp/jetty-docbase.2126115480907704550.12345/, jar:file:/opt/escheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources, jar:file:/opt/eschedul
er/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources],UNAVAILABLE}
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: javax.servlet.ServletContext.setInitParameter(Ljava/lang/String;Ljava/lang/String;)Z
        at org.springframework.boot.web.servlet.server.AbstractServletWebServerFactory.lambda$mergeInitializers$0(AbstractServletWebServerFactory.java:253)
        at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:66)
        at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:55)
        at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1454)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.server.Server.start(Server.java:415)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:382)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:108)
        at org.springframework.boot.web.embedded.jetty.JettyWebServer.<init>(JettyWebServer.java:86)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getJettyWebServer(JettyServletWebServerFactory.java:410)
        at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:153)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:181)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:154)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at cn.escheduler.api.ApiApplicationServer.main(ApiApplicationServer.java:33)
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.setInitParameter(Ljava/lang/String;Ljava/lang/String;)Z
        at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
        at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
        at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
        at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
        ... 29 common frames omitted
        
        
********************************* master-server ,没有log文件,.out信息:******************************        
more escheduler-master-server-Master.Hadoop.out
14:08:31.792 [main] DEBUG org.apache.commons.configuration.PropertiesConfiguration - FileName set to master.properties
14:08:31.796 [main] DEBUG org.apache.commons.configuration.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is master.properties
14:08:31.796 [main] DEBUG org.apache.commons.configuration.DefaultFileSystem - Could not locate file master.properties at null: no protocol: master.properties
14:08:31.799 [main] DEBUG org.apache.commons.configuration.ConfigurationUtils - Loading configuration from the context classpath (master.properties)
14:08:31.799 [main] DEBUG org.apache.commons.configuration.PropertiesConfiguration - Base path set to file:///opt/escheduler/conf/master.properties

**Comment by baiyibo** [comment]
怎么解决的呢？
