### ISSUE TITLE
[BUG] Alert Server startup faild

### ISSUE THREAD

**Issue by gary0416** [apache/incubator-dolphinscheduler#948]
/opt/escheduler/bin/escheduler-daemon.sh start alert-server

logs:
```
[INFO] 2019-09-30 16:10:46.589 org.apache.zookeeper.ZooKeeper:[100] - Client environment:java.io.tmpdir=/tmp
[INFO] 2019-09-30 16:10:46.589 org.apache.zookeeper.ZooKeeper:[100] - Client environment:java.compiler=<NA>
[INFO] 2019-09-30 16:10:46.590 org.apache.zookeeper.ZooKeeper:[100] - Client environment:os.name=Linux
[INFO] 2019-09-30 16:10:46.590 org.apache.zookeeper.ZooKeeper:[100] - Client environment:os.arch=amd64
[INFO] 2019-09-30 16:10:46.590 org.apache.zookeeper.ZooKeeper:[100] - Client environment:os.version=3.19.0-59-generic
[INFO] 2019-09-30 16:10:46.591 org.apache.zookeeper.ZooKeeper:[100] - Client environment:user.name=root
[INFO] 2019-09-30 16:10:46.591 org.apache.zookeeper.ZooKeeper:[100] - Client environment:user.home=/root
[INFO] 2019-09-30 16:10:46.591 org.apache.zookeeper.ZooKeeper:[100] - Client environment:user.dir=/opt/escheduler
[INFO] 2019-09-30 16:10:46.593 org.apache.zookeeper.ZooKeeper:[438] - Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=300000 watcher=org.apache.curator.ConnectionState@571a663c
[INFO] 2019-09-30 16:10:46.623 org.apache.zookeeper.ClientCnxn:[1032] - Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO] 2019-09-30 16:10:46.635 org.apache.zookeeper.ClientCnxn:[876] - Socket connection established to 127.0.0.1/127.0.0.1:2181, initiating session
[INFO] 2019-09-30 16:10:46.644 org.apache.zookeeper.ClientCnxn:[1299] - Session establishment complete on server 127.0.0.1/127.0.0.1:2181, sessionid = 0x1078ae4e7e50009, negotiated timeout = 40000
[INFO] 2019-09-30 16:10:46.688 org.apache.curator.framework.state.ConnectionStateManager:[228] - State change: CONNECTED
[INFO] 2019-09-30 16:10:46.691 cn.escheduler.common.zk.AbstractZKClient:[115] - state changed , current state : CONNECTED
[INFO] 2019-09-30 16:10:47.708 springfox.documentation.spring.web.PropertySourcedRequestMappingHandlerMapping:[69] - Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
[INFO] 2019-09-30 16:10:48.138 org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor:[171] - Initializing ExecutorService 'applicationTaskExecutor'
[INFO] 2019-09-30 16:10:48.635 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[160] - Context refreshed
[INFO] 2019-09-30 16:10:48.669 springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper:[163] - Found 1 custom documentation plugin(s)
[INFO] 2019-09-30 16:10:48.770 springfox.documentation.spring.web.scanners.ApiListingReferenceScanner:[41] - Scanning for api listing references
[INFO] 2019-09-30 16:10:49.363 springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator:[40] - Generating unique operation named: viewTreeUsingGET_1
[INFO] 2019-09-30 16:10:49.621 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Initializing Spring DispatcherServlet 'dispatcherServlet'
[INFO] 2019-09-30 16:10:49.622 org.springframework.web.servlet.DispatcherServlet:[524] - Initializing Servlet 'dispatcherServlet'
[INFO] 2019-09-30 16:10:49.632 org.springframework.web.servlet.DispatcherServlet:[546] - Completed initialization in 10 ms
[INFO] 2019-09-30 16:10:49.711 org.mortbay.log:[67] - Logging to Logger[org.mortbay.log] via org.mortbay.log.Slf4jLog
[INFO] 2019-09-30 16:10:49.816 org.eclipse.jetty.server.AbstractConnector:[292] - Started ServerConnector@2c08c787{HTTP/1.1,[http/1.1]}{0.0.0.0:7789}
[INFO] 2019-09-30 16:10:49.821 org.springframework.boot.web.embedded.jetty.JettyWebServer:[159] - Jetty started on port(s) 7789 (http/1.1) with context path '/'
[INFO] 2019-09-30 16:10:49.825 cn.escheduler.alert.AlertServer:[59] - Started AlertServer in 8.784 seconds (JVM running for 9.342)
[INFO] 2019-09-30 16:10:49.828 cn.escheduler.alert.AlertServer:[65] - Alert Server ready start!
[INFO] 2019-09-30 16:10:54.834 org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:[142] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2019-09-30 16:10:54.842 org.springframework.boot.SpringApplication:[858] - Application run failed
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at cn.escheduler.alert.AlertServer.main(AlertServer.java:81)
Caused by: java.lang.NullPointerException: null
	at cn.escheduler.alert.AlertServer.start(AlertServer.java:72)
	at cn.escheduler.alert.AlertServer.run(AlertServer.java:87)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
	... 3 common frames omitted
[INFO] 2019-09-30 16:10:54.851 org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor:[208] - Shutting down ExecutorService 'applicationTaskExecutor'
[INFO] 2019-09-30 16:10:54.868 com.alibaba.druid.pool.DruidDataSource:[1928] - {dataSource-1} closed
[INFO] 2019-09-30 16:10:54.881 org.eclipse.jetty.server.AbstractConnector:[341] - Stopped ServerConnector@2c08c787{HTTP/1.1,[http/1.1]}{0.0.0.0:7789}
[INFO] 2019-09-30 16:10:54.882 org.eclipse.jetty.server.session:[167] - node0 Stopped scavenging
[INFO] 2019-09-30 16:10:54.884 org.eclipse.jetty.server.handler.ContextHandler.application:[2345] - Destroying Spring FrameworkServlet 'dispatcherServlet'
[INFO] 2019-09-30 16:10:54.885 org.eclipse.jetty.server.handler.ContextHandler:[1045] - Stopped o.s.b.w.e.j.JettyEmbeddedWebAppContext@7b1e5e55{application,/,[file:///tmp/jetty-docbase.9040941700357288704.7789/, jar:file:/opt/escheduler/lib/swagger-bootstrap-ui-1.9.3.jar!/META-INF/resources, jar:file:/opt/escheduler/lib/springfox-swagger-ui-2.9.2.jar!/META-INF/resources],UNAVAILABLE}
```

https://github.com/apache/incubator-dolphinscheduler/blob/dev/escheduler-alert/src/main/java/cn/escheduler/alert/AlertServer.java#L72
```
List<Alert> alerts = alertDao.listWaitExecutionAlert();
```
**alertDao is null**

**Which version of Easy Scheduler:**
dev branch

**Requirement or improvement
code reviewed or tested?  
https://github.com/apache/incubator-dolphinscheduler/pull/872/commits/eb7c1694a7088d5d3ef7de2941f8686f9a6cd03a

**Comment by gary0416** [comment]
#953

**Comment by dailidong** [comment]
pr #953 resolved this issue!  I am closing this issue!
