### ISSUE TITLE
[BUG] zookeeper dashboard error

### ISSUE THREAD

**Issue by gary0416** [apache/incubator-dolphinscheduler#991]
![深度截图_选择区域_20191011191100](https://user-images.githubusercontent.com/2173239/66652051-4383ab80-ec67-11e9-8cbd-083330c92434.png)

Everything is -1.

```
root@34a2c3b68a9c:/opt/escheduler/logs# cat escheduler-api-server-34a2c3b68a9c.out   

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

Exception in thread "FourLetterCmd:ruok" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/Message
    at org.apache.zookeeper.client.FourLetterWordMain.<clinit>(FourLetterWordMain.java:35)
    at cn.escheduler.api.utils.ZooKeeperState$SendThread.run(ZooKeeperState.java:135)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.Message
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 2 more
Exception in thread "FourLetterCmd:ruok" java.lang.NoClassDefFoundError: Could not initialize class org.apache.zookeeper.client.FourLetterWordMain
    at cn.escheduler.api.utils.ZooKeeperState$SendThread.run(ZooKeeperState.java:135)
```

**Which version of Easy Scheduler:**
dev branch

log4j jar is missing.

**Comment by gary0416** [comment]
Sorry, duplicate with #967
